// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: admin.proto

#include "admin.pb.h"
#include "admin.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace admin {

static const char* AdminService_method_names[] = {
  "/admin.AdminService/GetUsers",
  "/admin.AdminService/GetUser",
  "/admin.AdminService/CreateUser",
  "/admin.AdminService/UpdateUser",
  "/admin.AdminService/DeleteUser",
  "/admin.AdminService/GetRoles",
  "/admin.AdminService/GetRole",
  "/admin.AdminService/CreateRole",
  "/admin.AdminService/UpdateRole",
  "/admin.AdminService/DeleteRole",
  "/admin.AdminService/GetPermissions",
  "/admin.AdminService/GetSystemSettings",
  "/admin.AdminService/UpdateSystemSettings",
};

std::unique_ptr< AdminService::Stub> AdminService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AdminService::Stub> stub(new AdminService::Stub(channel, options));
  return stub;
}

AdminService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetUsers_(AdminService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUser_(AdminService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateUser_(AdminService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateUser_(AdminService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteUser_(AdminService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRoles_(AdminService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRole_(AdminService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateRole_(AdminService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateRole_(AdminService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteRole_(AdminService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPermissions_(AdminService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSystemSettings_(AdminService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateSystemSettings_(AdminService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AdminService::Stub::GetUsers(::grpc::ClientContext* context, const ::admin::GetUsersRequest& request, ::admin::GetUsersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::GetUsersRequest, ::admin::GetUsersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUsers_, context, request, response);
}

void AdminService::Stub::async::GetUsers(::grpc::ClientContext* context, const ::admin::GetUsersRequest* request, ::admin::GetUsersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::GetUsersRequest, ::admin::GetUsersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUsers_, context, request, response, std::move(f));
}

void AdminService::Stub::async::GetUsers(::grpc::ClientContext* context, const ::admin::GetUsersRequest* request, ::admin::GetUsersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUsers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::GetUsersResponse>* AdminService::Stub::PrepareAsyncGetUsersRaw(::grpc::ClientContext* context, const ::admin::GetUsersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::GetUsersResponse, ::admin::GetUsersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUsers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::GetUsersResponse>* AdminService::Stub::AsyncGetUsersRaw(::grpc::ClientContext* context, const ::admin::GetUsersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUsersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::GetUser(::grpc::ClientContext* context, const ::admin::GetUserRequest& request, ::admin::User* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::GetUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUser_, context, request, response);
}

void AdminService::Stub::async::GetUser(::grpc::ClientContext* context, const ::admin::GetUserRequest* request, ::admin::User* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::GetUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUser_, context, request, response, std::move(f));
}

void AdminService::Stub::async::GetUser(::grpc::ClientContext* context, const ::admin::GetUserRequest* request, ::admin::User* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::User>* AdminService::Stub::PrepareAsyncGetUserRaw(::grpc::ClientContext* context, const ::admin::GetUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::User, ::admin::GetUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::User>* AdminService::Stub::AsyncGetUserRaw(::grpc::ClientContext* context, const ::admin::GetUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::CreateUser(::grpc::ClientContext* context, const ::admin::CreateUserRequest& request, ::admin::User* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::CreateUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateUser_, context, request, response);
}

void AdminService::Stub::async::CreateUser(::grpc::ClientContext* context, const ::admin::CreateUserRequest* request, ::admin::User* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::CreateUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateUser_, context, request, response, std::move(f));
}

void AdminService::Stub::async::CreateUser(::grpc::ClientContext* context, const ::admin::CreateUserRequest* request, ::admin::User* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::User>* AdminService::Stub::PrepareAsyncCreateUserRaw(::grpc::ClientContext* context, const ::admin::CreateUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::User, ::admin::CreateUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::User>* AdminService::Stub::AsyncCreateUserRaw(::grpc::ClientContext* context, const ::admin::CreateUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::UpdateUser(::grpc::ClientContext* context, const ::admin::UpdateUserRequest& request, ::admin::User* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::UpdateUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateUser_, context, request, response);
}

void AdminService::Stub::async::UpdateUser(::grpc::ClientContext* context, const ::admin::UpdateUserRequest* request, ::admin::User* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::UpdateUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUser_, context, request, response, std::move(f));
}

void AdminService::Stub::async::UpdateUser(::grpc::ClientContext* context, const ::admin::UpdateUserRequest* request, ::admin::User* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::User>* AdminService::Stub::PrepareAsyncUpdateUserRaw(::grpc::ClientContext* context, const ::admin::UpdateUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::User, ::admin::UpdateUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::User>* AdminService::Stub::AsyncUpdateUserRaw(::grpc::ClientContext* context, const ::admin::UpdateUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::DeleteUser(::grpc::ClientContext* context, const ::admin::DeleteUserRequest& request, ::admin::EmptyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::DeleteUserRequest, ::admin::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteUser_, context, request, response);
}

void AdminService::Stub::async::DeleteUser(::grpc::ClientContext* context, const ::admin::DeleteUserRequest* request, ::admin::EmptyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::DeleteUserRequest, ::admin::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteUser_, context, request, response, std::move(f));
}

void AdminService::Stub::async::DeleteUser(::grpc::ClientContext* context, const ::admin::DeleteUserRequest* request, ::admin::EmptyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::EmptyResponse>* AdminService::Stub::PrepareAsyncDeleteUserRaw(::grpc::ClientContext* context, const ::admin::DeleteUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::EmptyResponse, ::admin::DeleteUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::EmptyResponse>* AdminService::Stub::AsyncDeleteUserRaw(::grpc::ClientContext* context, const ::admin::DeleteUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::GetRoles(::grpc::ClientContext* context, const ::admin::GetRolesRequest& request, ::admin::GetRolesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::GetRolesRequest, ::admin::GetRolesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRoles_, context, request, response);
}

void AdminService::Stub::async::GetRoles(::grpc::ClientContext* context, const ::admin::GetRolesRequest* request, ::admin::GetRolesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::GetRolesRequest, ::admin::GetRolesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRoles_, context, request, response, std::move(f));
}

void AdminService::Stub::async::GetRoles(::grpc::ClientContext* context, const ::admin::GetRolesRequest* request, ::admin::GetRolesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRoles_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::GetRolesResponse>* AdminService::Stub::PrepareAsyncGetRolesRaw(::grpc::ClientContext* context, const ::admin::GetRolesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::GetRolesResponse, ::admin::GetRolesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRoles_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::GetRolesResponse>* AdminService::Stub::AsyncGetRolesRaw(::grpc::ClientContext* context, const ::admin::GetRolesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRolesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::GetRole(::grpc::ClientContext* context, const ::admin::GetRoleRequest& request, ::admin::Role* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::GetRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRole_, context, request, response);
}

void AdminService::Stub::async::GetRole(::grpc::ClientContext* context, const ::admin::GetRoleRequest* request, ::admin::Role* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::GetRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRole_, context, request, response, std::move(f));
}

void AdminService::Stub::async::GetRole(::grpc::ClientContext* context, const ::admin::GetRoleRequest* request, ::admin::Role* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRole_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::Role>* AdminService::Stub::PrepareAsyncGetRoleRaw(::grpc::ClientContext* context, const ::admin::GetRoleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::Role, ::admin::GetRoleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRole_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::Role>* AdminService::Stub::AsyncGetRoleRaw(::grpc::ClientContext* context, const ::admin::GetRoleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRoleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::CreateRole(::grpc::ClientContext* context, const ::admin::CreateRoleRequest& request, ::admin::Role* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::CreateRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateRole_, context, request, response);
}

void AdminService::Stub::async::CreateRole(::grpc::ClientContext* context, const ::admin::CreateRoleRequest* request, ::admin::Role* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::CreateRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateRole_, context, request, response, std::move(f));
}

void AdminService::Stub::async::CreateRole(::grpc::ClientContext* context, const ::admin::CreateRoleRequest* request, ::admin::Role* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateRole_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::Role>* AdminService::Stub::PrepareAsyncCreateRoleRaw(::grpc::ClientContext* context, const ::admin::CreateRoleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::Role, ::admin::CreateRoleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateRole_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::Role>* AdminService::Stub::AsyncCreateRoleRaw(::grpc::ClientContext* context, const ::admin::CreateRoleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRoleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::UpdateRole(::grpc::ClientContext* context, const ::admin::UpdateRoleRequest& request, ::admin::Role* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::UpdateRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateRole_, context, request, response);
}

void AdminService::Stub::async::UpdateRole(::grpc::ClientContext* context, const ::admin::UpdateRoleRequest* request, ::admin::Role* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::UpdateRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateRole_, context, request, response, std::move(f));
}

void AdminService::Stub::async::UpdateRole(::grpc::ClientContext* context, const ::admin::UpdateRoleRequest* request, ::admin::Role* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateRole_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::Role>* AdminService::Stub::PrepareAsyncUpdateRoleRaw(::grpc::ClientContext* context, const ::admin::UpdateRoleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::Role, ::admin::UpdateRoleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateRole_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::Role>* AdminService::Stub::AsyncUpdateRoleRaw(::grpc::ClientContext* context, const ::admin::UpdateRoleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateRoleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::DeleteRole(::grpc::ClientContext* context, const ::admin::DeleteRoleRequest& request, ::admin::EmptyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::DeleteRoleRequest, ::admin::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteRole_, context, request, response);
}

void AdminService::Stub::async::DeleteRole(::grpc::ClientContext* context, const ::admin::DeleteRoleRequest* request, ::admin::EmptyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::DeleteRoleRequest, ::admin::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteRole_, context, request, response, std::move(f));
}

void AdminService::Stub::async::DeleteRole(::grpc::ClientContext* context, const ::admin::DeleteRoleRequest* request, ::admin::EmptyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteRole_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::EmptyResponse>* AdminService::Stub::PrepareAsyncDeleteRoleRaw(::grpc::ClientContext* context, const ::admin::DeleteRoleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::EmptyResponse, ::admin::DeleteRoleRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteRole_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::EmptyResponse>* AdminService::Stub::AsyncDeleteRoleRaw(::grpc::ClientContext* context, const ::admin::DeleteRoleRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRoleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::GetPermissions(::grpc::ClientContext* context, const ::admin::GetPermissionsRequest& request, ::admin::GetPermissionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::GetPermissionsRequest, ::admin::GetPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPermissions_, context, request, response);
}

void AdminService::Stub::async::GetPermissions(::grpc::ClientContext* context, const ::admin::GetPermissionsRequest* request, ::admin::GetPermissionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::GetPermissionsRequest, ::admin::GetPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPermissions_, context, request, response, std::move(f));
}

void AdminService::Stub::async::GetPermissions(::grpc::ClientContext* context, const ::admin::GetPermissionsRequest* request, ::admin::GetPermissionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPermissions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::GetPermissionsResponse>* AdminService::Stub::PrepareAsyncGetPermissionsRaw(::grpc::ClientContext* context, const ::admin::GetPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::GetPermissionsResponse, ::admin::GetPermissionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPermissions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::GetPermissionsResponse>* AdminService::Stub::AsyncGetPermissionsRaw(::grpc::ClientContext* context, const ::admin::GetPermissionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPermissionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::GetSystemSettings(::grpc::ClientContext* context, const ::admin::EmptyRequest& request, ::admin::SystemSettings* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::EmptyRequest, ::admin::SystemSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSystemSettings_, context, request, response);
}

void AdminService::Stub::async::GetSystemSettings(::grpc::ClientContext* context, const ::admin::EmptyRequest* request, ::admin::SystemSettings* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::EmptyRequest, ::admin::SystemSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSystemSettings_, context, request, response, std::move(f));
}

void AdminService::Stub::async::GetSystemSettings(::grpc::ClientContext* context, const ::admin::EmptyRequest* request, ::admin::SystemSettings* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSystemSettings_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::SystemSettings>* AdminService::Stub::PrepareAsyncGetSystemSettingsRaw(::grpc::ClientContext* context, const ::admin::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::SystemSettings, ::admin::EmptyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSystemSettings_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::SystemSettings>* AdminService::Stub::AsyncGetSystemSettingsRaw(::grpc::ClientContext* context, const ::admin::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSystemSettingsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AdminService::Stub::UpdateSystemSettings(::grpc::ClientContext* context, const ::admin::UpdateSystemSettingsRequest& request, ::admin::SystemSettings* response) {
  return ::grpc::internal::BlockingUnaryCall< ::admin::UpdateSystemSettingsRequest, ::admin::SystemSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateSystemSettings_, context, request, response);
}

void AdminService::Stub::async::UpdateSystemSettings(::grpc::ClientContext* context, const ::admin::UpdateSystemSettingsRequest* request, ::admin::SystemSettings* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::admin::UpdateSystemSettingsRequest, ::admin::SystemSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSystemSettings_, context, request, response, std::move(f));
}

void AdminService::Stub::async::UpdateSystemSettings(::grpc::ClientContext* context, const ::admin::UpdateSystemSettingsRequest* request, ::admin::SystemSettings* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSystemSettings_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::admin::SystemSettings>* AdminService::Stub::PrepareAsyncUpdateSystemSettingsRaw(::grpc::ClientContext* context, const ::admin::UpdateSystemSettingsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::admin::SystemSettings, ::admin::UpdateSystemSettingsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateSystemSettings_, context, request);
}

::grpc::ClientAsyncResponseReader< ::admin::SystemSettings>* AdminService::Stub::AsyncUpdateSystemSettingsRaw(::grpc::ClientContext* context, const ::admin::UpdateSystemSettingsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateSystemSettingsRaw(context, request, cq);
  result->StartCall();
  return result;
}

AdminService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::GetUsersRequest, ::admin::GetUsersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::GetUsersRequest* req,
             ::admin::GetUsersResponse* resp) {
               return service->GetUsers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::GetUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::GetUserRequest* req,
             ::admin::User* resp) {
               return service->GetUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::CreateUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::CreateUserRequest* req,
             ::admin::User* resp) {
               return service->CreateUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::UpdateUserRequest, ::admin::User, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::UpdateUserRequest* req,
             ::admin::User* resp) {
               return service->UpdateUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::DeleteUserRequest, ::admin::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::DeleteUserRequest* req,
             ::admin::EmptyResponse* resp) {
               return service->DeleteUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::GetRolesRequest, ::admin::GetRolesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::GetRolesRequest* req,
             ::admin::GetRolesResponse* resp) {
               return service->GetRoles(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::GetRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::GetRoleRequest* req,
             ::admin::Role* resp) {
               return service->GetRole(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::CreateRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::CreateRoleRequest* req,
             ::admin::Role* resp) {
               return service->CreateRole(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::UpdateRoleRequest, ::admin::Role, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::UpdateRoleRequest* req,
             ::admin::Role* resp) {
               return service->UpdateRole(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::DeleteRoleRequest, ::admin::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::DeleteRoleRequest* req,
             ::admin::EmptyResponse* resp) {
               return service->DeleteRole(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::GetPermissionsRequest, ::admin::GetPermissionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::GetPermissionsRequest* req,
             ::admin::GetPermissionsResponse* resp) {
               return service->GetPermissions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::EmptyRequest, ::admin::SystemSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::EmptyRequest* req,
             ::admin::SystemSettings* resp) {
               return service->GetSystemSettings(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AdminService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AdminService::Service, ::admin::UpdateSystemSettingsRequest, ::admin::SystemSettings, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AdminService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::admin::UpdateSystemSettingsRequest* req,
             ::admin::SystemSettings* resp) {
               return service->UpdateSystemSettings(ctx, req, resp);
             }, this)));
}

AdminService::Service::~Service() {
}

::grpc::Status AdminService::Service::GetUsers(::grpc::ServerContext* context, const ::admin::GetUsersRequest* request, ::admin::GetUsersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::GetUser(::grpc::ServerContext* context, const ::admin::GetUserRequest* request, ::admin::User* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::CreateUser(::grpc::ServerContext* context, const ::admin::CreateUserRequest* request, ::admin::User* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::UpdateUser(::grpc::ServerContext* context, const ::admin::UpdateUserRequest* request, ::admin::User* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::DeleteUser(::grpc::ServerContext* context, const ::admin::DeleteUserRequest* request, ::admin::EmptyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::GetRoles(::grpc::ServerContext* context, const ::admin::GetRolesRequest* request, ::admin::GetRolesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::GetRole(::grpc::ServerContext* context, const ::admin::GetRoleRequest* request, ::admin::Role* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::CreateRole(::grpc::ServerContext* context, const ::admin::CreateRoleRequest* request, ::admin::Role* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::UpdateRole(::grpc::ServerContext* context, const ::admin::UpdateRoleRequest* request, ::admin::Role* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::DeleteRole(::grpc::ServerContext* context, const ::admin::DeleteRoleRequest* request, ::admin::EmptyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::GetPermissions(::grpc::ServerContext* context, const ::admin::GetPermissionsRequest* request, ::admin::GetPermissionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::GetSystemSettings(::grpc::ServerContext* context, const ::admin::EmptyRequest* request, ::admin::SystemSettings* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AdminService::Service::UpdateSystemSettings(::grpc::ServerContext* context, const ::admin::UpdateSystemSettingsRequest* request, ::admin::SystemSettings* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace admin

