// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: asset.proto

#include "asset.pb.h"
#include "asset.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace asset {

static const char* AssetService_method_names[] = {
  "/asset.AssetService/CreateAsset",
  "/asset.AssetService/GetAsset",
  "/asset.AssetService/UpdateAssetStatus",
  "/asset.AssetService/ListAssets",
  "/asset.AssetService/GetAssetStatistics",
  "/asset.AssetService/BatchScanEPC",
  "/asset.AssetService/StartInventoryTask",
  "/asset.AssetService/GetInventoryTask",
  "/asset.AssetService/HealthCheck",
  "/asset.AssetService/GetMetrics",
  "/asset.AssetService/GetRecentDecisions",
  "/asset.AssetService/ReportDecision",
};

std::unique_ptr< AssetService::Stub> AssetService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AssetService::Stub> stub(new AssetService::Stub(channel, options));
  return stub;
}

AssetService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateAsset_(AssetService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAsset_(AssetService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateAssetStatus_(AssetService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListAssets_(AssetService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAssetStatistics_(AssetService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchScanEPC_(AssetService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StartInventoryTask_(AssetService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetInventoryTask_(AssetService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HealthCheck_(AssetService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMetrics_(AssetService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRecentDecisions_(AssetService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportDecision_(AssetService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AssetService::Stub::CreateAsset(::grpc::ClientContext* context, const ::asset::CreateAssetRequest& request, ::asset::CreateAssetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::CreateAssetRequest, ::asset::CreateAssetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateAsset_, context, request, response);
}

void AssetService::Stub::async::CreateAsset(::grpc::ClientContext* context, const ::asset::CreateAssetRequest* request, ::asset::CreateAssetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::CreateAssetRequest, ::asset::CreateAssetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAsset_, context, request, response, std::move(f));
}

void AssetService::Stub::async::CreateAsset(::grpc::ClientContext* context, const ::asset::CreateAssetRequest* request, ::asset::CreateAssetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateAsset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::CreateAssetResponse>* AssetService::Stub::PrepareAsyncCreateAssetRaw(::grpc::ClientContext* context, const ::asset::CreateAssetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::CreateAssetResponse, ::asset::CreateAssetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateAsset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::CreateAssetResponse>* AssetService::Stub::AsyncCreateAssetRaw(::grpc::ClientContext* context, const ::asset::CreateAssetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateAssetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::GetAsset(::grpc::ClientContext* context, const ::asset::GetAssetRequest& request, ::asset::GetAssetResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::GetAssetRequest, ::asset::GetAssetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAsset_, context, request, response);
}

void AssetService::Stub::async::GetAsset(::grpc::ClientContext* context, const ::asset::GetAssetRequest* request, ::asset::GetAssetResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::GetAssetRequest, ::asset::GetAssetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAsset_, context, request, response, std::move(f));
}

void AssetService::Stub::async::GetAsset(::grpc::ClientContext* context, const ::asset::GetAssetRequest* request, ::asset::GetAssetResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAsset_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::GetAssetResponse>* AssetService::Stub::PrepareAsyncGetAssetRaw(::grpc::ClientContext* context, const ::asset::GetAssetRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::GetAssetResponse, ::asset::GetAssetRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAsset_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::GetAssetResponse>* AssetService::Stub::AsyncGetAssetRaw(::grpc::ClientContext* context, const ::asset::GetAssetRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAssetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::UpdateAssetStatus(::grpc::ClientContext* context, const ::asset::UpdateAssetStatusRequest& request, ::asset::UpdateAssetStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::UpdateAssetStatusRequest, ::asset::UpdateAssetStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateAssetStatus_, context, request, response);
}

void AssetService::Stub::async::UpdateAssetStatus(::grpc::ClientContext* context, const ::asset::UpdateAssetStatusRequest* request, ::asset::UpdateAssetStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::UpdateAssetStatusRequest, ::asset::UpdateAssetStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateAssetStatus_, context, request, response, std::move(f));
}

void AssetService::Stub::async::UpdateAssetStatus(::grpc::ClientContext* context, const ::asset::UpdateAssetStatusRequest* request, ::asset::UpdateAssetStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateAssetStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::UpdateAssetStatusResponse>* AssetService::Stub::PrepareAsyncUpdateAssetStatusRaw(::grpc::ClientContext* context, const ::asset::UpdateAssetStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::UpdateAssetStatusResponse, ::asset::UpdateAssetStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateAssetStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::UpdateAssetStatusResponse>* AssetService::Stub::AsyncUpdateAssetStatusRaw(::grpc::ClientContext* context, const ::asset::UpdateAssetStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateAssetStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::ListAssets(::grpc::ClientContext* context, const ::asset::ListAssetsRequest& request, ::asset::ListAssetsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::ListAssetsRequest, ::asset::ListAssetsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListAssets_, context, request, response);
}

void AssetService::Stub::async::ListAssets(::grpc::ClientContext* context, const ::asset::ListAssetsRequest* request, ::asset::ListAssetsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::ListAssetsRequest, ::asset::ListAssetsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAssets_, context, request, response, std::move(f));
}

void AssetService::Stub::async::ListAssets(::grpc::ClientContext* context, const ::asset::ListAssetsRequest* request, ::asset::ListAssetsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAssets_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::ListAssetsResponse>* AssetService::Stub::PrepareAsyncListAssetsRaw(::grpc::ClientContext* context, const ::asset::ListAssetsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::ListAssetsResponse, ::asset::ListAssetsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListAssets_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::ListAssetsResponse>* AssetService::Stub::AsyncListAssetsRaw(::grpc::ClientContext* context, const ::asset::ListAssetsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListAssetsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::GetAssetStatistics(::grpc::ClientContext* context, const ::asset::GetAssetStatisticsRequest& request, ::asset::GetAssetStatisticsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::GetAssetStatisticsRequest, ::asset::GetAssetStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAssetStatistics_, context, request, response);
}

void AssetService::Stub::async::GetAssetStatistics(::grpc::ClientContext* context, const ::asset::GetAssetStatisticsRequest* request, ::asset::GetAssetStatisticsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::GetAssetStatisticsRequest, ::asset::GetAssetStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAssetStatistics_, context, request, response, std::move(f));
}

void AssetService::Stub::async::GetAssetStatistics(::grpc::ClientContext* context, const ::asset::GetAssetStatisticsRequest* request, ::asset::GetAssetStatisticsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAssetStatistics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::GetAssetStatisticsResponse>* AssetService::Stub::PrepareAsyncGetAssetStatisticsRaw(::grpc::ClientContext* context, const ::asset::GetAssetStatisticsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::GetAssetStatisticsResponse, ::asset::GetAssetStatisticsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAssetStatistics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::GetAssetStatisticsResponse>* AssetService::Stub::AsyncGetAssetStatisticsRaw(::grpc::ClientContext* context, const ::asset::GetAssetStatisticsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAssetStatisticsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::BatchScanEPC(::grpc::ClientContext* context, const ::asset::BatchScanRequest& request, ::asset::BatchScanResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::BatchScanRequest, ::asset::BatchScanResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchScanEPC_, context, request, response);
}

void AssetService::Stub::async::BatchScanEPC(::grpc::ClientContext* context, const ::asset::BatchScanRequest* request, ::asset::BatchScanResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::BatchScanRequest, ::asset::BatchScanResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchScanEPC_, context, request, response, std::move(f));
}

void AssetService::Stub::async::BatchScanEPC(::grpc::ClientContext* context, const ::asset::BatchScanRequest* request, ::asset::BatchScanResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchScanEPC_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::BatchScanResponse>* AssetService::Stub::PrepareAsyncBatchScanEPCRaw(::grpc::ClientContext* context, const ::asset::BatchScanRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::BatchScanResponse, ::asset::BatchScanRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchScanEPC_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::BatchScanResponse>* AssetService::Stub::AsyncBatchScanEPCRaw(::grpc::ClientContext* context, const ::asset::BatchScanRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchScanEPCRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::StartInventoryTask(::grpc::ClientContext* context, const ::asset::StartInventoryTaskRequest& request, ::asset::StartInventoryTaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::StartInventoryTaskRequest, ::asset::StartInventoryTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_StartInventoryTask_, context, request, response);
}

void AssetService::Stub::async::StartInventoryTask(::grpc::ClientContext* context, const ::asset::StartInventoryTaskRequest* request, ::asset::StartInventoryTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::StartInventoryTaskRequest, ::asset::StartInventoryTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartInventoryTask_, context, request, response, std::move(f));
}

void AssetService::Stub::async::StartInventoryTask(::grpc::ClientContext* context, const ::asset::StartInventoryTaskRequest* request, ::asset::StartInventoryTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_StartInventoryTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::StartInventoryTaskResponse>* AssetService::Stub::PrepareAsyncStartInventoryTaskRaw(::grpc::ClientContext* context, const ::asset::StartInventoryTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::StartInventoryTaskResponse, ::asset::StartInventoryTaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_StartInventoryTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::StartInventoryTaskResponse>* AssetService::Stub::AsyncStartInventoryTaskRaw(::grpc::ClientContext* context, const ::asset::StartInventoryTaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartInventoryTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::GetInventoryTask(::grpc::ClientContext* context, const ::asset::GetInventoryTaskRequest& request, ::asset::GetInventoryTaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::GetInventoryTaskRequest, ::asset::GetInventoryTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetInventoryTask_, context, request, response);
}

void AssetService::Stub::async::GetInventoryTask(::grpc::ClientContext* context, const ::asset::GetInventoryTaskRequest* request, ::asset::GetInventoryTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::GetInventoryTaskRequest, ::asset::GetInventoryTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInventoryTask_, context, request, response, std::move(f));
}

void AssetService::Stub::async::GetInventoryTask(::grpc::ClientContext* context, const ::asset::GetInventoryTaskRequest* request, ::asset::GetInventoryTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInventoryTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::GetInventoryTaskResponse>* AssetService::Stub::PrepareAsyncGetInventoryTaskRaw(::grpc::ClientContext* context, const ::asset::GetInventoryTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::GetInventoryTaskResponse, ::asset::GetInventoryTaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetInventoryTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::GetInventoryTaskResponse>* AssetService::Stub::AsyncGetInventoryTaskRaw(::grpc::ClientContext* context, const ::asset::GetInventoryTaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetInventoryTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::HealthCheck(::grpc::ClientContext* context, const ::asset::HealthCheckRequest& request, ::asset::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::HealthCheckRequest, ::asset::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HealthCheck_, context, request, response);
}

void AssetService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::asset::HealthCheckRequest* request, ::asset::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::HealthCheckRequest, ::asset::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, std::move(f));
}

void AssetService::Stub::async::HealthCheck(::grpc::ClientContext* context, const ::asset::HealthCheckRequest* request, ::asset::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::HealthCheckResponse>* AssetService::Stub::PrepareAsyncHealthCheckRaw(::grpc::ClientContext* context, const ::asset::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::HealthCheckResponse, ::asset::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::HealthCheckResponse>* AssetService::Stub::AsyncHealthCheckRaw(::grpc::ClientContext* context, const ::asset::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::GetMetrics(::grpc::ClientContext* context, const ::asset::GetMetricsRequest& request, ::asset::GetMetricsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::GetMetricsRequest, ::asset::GetMetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMetrics_, context, request, response);
}

void AssetService::Stub::async::GetMetrics(::grpc::ClientContext* context, const ::asset::GetMetricsRequest* request, ::asset::GetMetricsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::GetMetricsRequest, ::asset::GetMetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetrics_, context, request, response, std::move(f));
}

void AssetService::Stub::async::GetMetrics(::grpc::ClientContext* context, const ::asset::GetMetricsRequest* request, ::asset::GetMetricsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetrics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::GetMetricsResponse>* AssetService::Stub::PrepareAsyncGetMetricsRaw(::grpc::ClientContext* context, const ::asset::GetMetricsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::GetMetricsResponse, ::asset::GetMetricsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMetrics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::GetMetricsResponse>* AssetService::Stub::AsyncGetMetricsRaw(::grpc::ClientContext* context, const ::asset::GetMetricsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetricsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::GetRecentDecisions(::grpc::ClientContext* context, const ::asset::GetRecentDecisionsRequest& request, ::asset::GetRecentDecisionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::GetRecentDecisionsRequest, ::asset::GetRecentDecisionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRecentDecisions_, context, request, response);
}

void AssetService::Stub::async::GetRecentDecisions(::grpc::ClientContext* context, const ::asset::GetRecentDecisionsRequest* request, ::asset::GetRecentDecisionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::GetRecentDecisionsRequest, ::asset::GetRecentDecisionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRecentDecisions_, context, request, response, std::move(f));
}

void AssetService::Stub::async::GetRecentDecisions(::grpc::ClientContext* context, const ::asset::GetRecentDecisionsRequest* request, ::asset::GetRecentDecisionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRecentDecisions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::GetRecentDecisionsResponse>* AssetService::Stub::PrepareAsyncGetRecentDecisionsRaw(::grpc::ClientContext* context, const ::asset::GetRecentDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::GetRecentDecisionsResponse, ::asset::GetRecentDecisionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRecentDecisions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::GetRecentDecisionsResponse>* AssetService::Stub::AsyncGetRecentDecisionsRaw(::grpc::ClientContext* context, const ::asset::GetRecentDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRecentDecisionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AssetService::Stub::ReportDecision(::grpc::ClientContext* context, const ::asset::ReportDecisionRequest& request, ::asset::ReportDecisionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::asset::ReportDecisionRequest, ::asset::ReportDecisionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportDecision_, context, request, response);
}

void AssetService::Stub::async::ReportDecision(::grpc::ClientContext* context, const ::asset::ReportDecisionRequest* request, ::asset::ReportDecisionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::asset::ReportDecisionRequest, ::asset::ReportDecisionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportDecision_, context, request, response, std::move(f));
}

void AssetService::Stub::async::ReportDecision(::grpc::ClientContext* context, const ::asset::ReportDecisionRequest* request, ::asset::ReportDecisionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportDecision_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::asset::ReportDecisionResponse>* AssetService::Stub::PrepareAsyncReportDecisionRaw(::grpc::ClientContext* context, const ::asset::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::asset::ReportDecisionResponse, ::asset::ReportDecisionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportDecision_, context, request);
}

::grpc::ClientAsyncResponseReader< ::asset::ReportDecisionResponse>* AssetService::Stub::AsyncReportDecisionRaw(::grpc::ClientContext* context, const ::asset::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportDecisionRaw(context, request, cq);
  result->StartCall();
  return result;
}

AssetService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::CreateAssetRequest, ::asset::CreateAssetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::CreateAssetRequest* req,
             ::asset::CreateAssetResponse* resp) {
               return service->CreateAsset(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::GetAssetRequest, ::asset::GetAssetResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::GetAssetRequest* req,
             ::asset::GetAssetResponse* resp) {
               return service->GetAsset(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::UpdateAssetStatusRequest, ::asset::UpdateAssetStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::UpdateAssetStatusRequest* req,
             ::asset::UpdateAssetStatusResponse* resp) {
               return service->UpdateAssetStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::ListAssetsRequest, ::asset::ListAssetsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::ListAssetsRequest* req,
             ::asset::ListAssetsResponse* resp) {
               return service->ListAssets(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::GetAssetStatisticsRequest, ::asset::GetAssetStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::GetAssetStatisticsRequest* req,
             ::asset::GetAssetStatisticsResponse* resp) {
               return service->GetAssetStatistics(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::BatchScanRequest, ::asset::BatchScanResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::BatchScanRequest* req,
             ::asset::BatchScanResponse* resp) {
               return service->BatchScanEPC(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::StartInventoryTaskRequest, ::asset::StartInventoryTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::StartInventoryTaskRequest* req,
             ::asset::StartInventoryTaskResponse* resp) {
               return service->StartInventoryTask(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::GetInventoryTaskRequest, ::asset::GetInventoryTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::GetInventoryTaskRequest* req,
             ::asset::GetInventoryTaskResponse* resp) {
               return service->GetInventoryTask(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::HealthCheckRequest, ::asset::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::HealthCheckRequest* req,
             ::asset::HealthCheckResponse* resp) {
               return service->HealthCheck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::GetMetricsRequest, ::asset::GetMetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::GetMetricsRequest* req,
             ::asset::GetMetricsResponse* resp) {
               return service->GetMetrics(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::GetRecentDecisionsRequest, ::asset::GetRecentDecisionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::GetRecentDecisionsRequest* req,
             ::asset::GetRecentDecisionsResponse* resp) {
               return service->GetRecentDecisions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AssetService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AssetService::Service, ::asset::ReportDecisionRequest, ::asset::ReportDecisionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AssetService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::asset::ReportDecisionRequest* req,
             ::asset::ReportDecisionResponse* resp) {
               return service->ReportDecision(ctx, req, resp);
             }, this)));
}

AssetService::Service::~Service() {
}

::grpc::Status AssetService::Service::CreateAsset(::grpc::ServerContext* context, const ::asset::CreateAssetRequest* request, ::asset::CreateAssetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::GetAsset(::grpc::ServerContext* context, const ::asset::GetAssetRequest* request, ::asset::GetAssetResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::UpdateAssetStatus(::grpc::ServerContext* context, const ::asset::UpdateAssetStatusRequest* request, ::asset::UpdateAssetStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::ListAssets(::grpc::ServerContext* context, const ::asset::ListAssetsRequest* request, ::asset::ListAssetsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::GetAssetStatistics(::grpc::ServerContext* context, const ::asset::GetAssetStatisticsRequest* request, ::asset::GetAssetStatisticsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::BatchScanEPC(::grpc::ServerContext* context, const ::asset::BatchScanRequest* request, ::asset::BatchScanResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::StartInventoryTask(::grpc::ServerContext* context, const ::asset::StartInventoryTaskRequest* request, ::asset::StartInventoryTaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::GetInventoryTask(::grpc::ServerContext* context, const ::asset::GetInventoryTaskRequest* request, ::asset::GetInventoryTaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::HealthCheck(::grpc::ServerContext* context, const ::asset::HealthCheckRequest* request, ::asset::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::GetMetrics(::grpc::ServerContext* context, const ::asset::GetMetricsRequest* request, ::asset::GetMetricsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::GetRecentDecisions(::grpc::ServerContext* context, const ::asset::GetRecentDecisionsRequest* request, ::asset::GetRecentDecisionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AssetService::Service::ReportDecision(::grpc::ServerContext* context, const ::asset::ReportDecisionRequest* request, ::asset::ReportDecisionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace asset

