// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bi.proto
#ifndef GRPC_bi_2eproto__INCLUDED
#define GRPC_bi_2eproto__INCLUDED

#include "bi.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace bi {

class BIReportService final {
 public:
  static constexpr char const* service_full_name() {
    return "bi.BIReportService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::bi::GenerateReportResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GenerateReportResponse>> AsyncGenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GenerateReportResponse>>(AsyncGenerateReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GenerateReportResponse>> PrepareAsyncGenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GenerateReportResponse>>(PrepareAsyncGenerateReportRaw(context, request, cq));
    }
    virtual ::grpc::Status ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::bi::ExportReportResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ExportReportResponse>> AsyncExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ExportReportResponse>>(AsyncExportReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ExportReportResponse>> PrepareAsyncExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ExportReportResponse>>(PrepareAsyncExportReportRaw(context, request, cq));
    }
    virtual ::grpc::Status GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::bi::GetReportsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetReportsResponse>> AsyncGetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetReportsResponse>>(AsyncGetReportsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetReportsResponse>> PrepareAsyncGetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetReportsResponse>>(PrepareAsyncGetReportsRaw(context, request, cq));
    }
    virtual ::grpc::Status GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::bi::ReportResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ReportResult>> AsyncGetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ReportResult>>(AsyncGetReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ReportResult>> PrepareAsyncGetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::ReportResult>>(PrepareAsyncGetReportRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::bi::DeleteReportResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteReportResponse>> AsyncDeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteReportResponse>>(AsyncDeleteReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteReportResponse>> PrepareAsyncDeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteReportResponse>>(PrepareAsyncDeleteReportRaw(context, request, cq));
    }
    virtual ::grpc::Status AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::bi::AddTaskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::AddTaskResponse>> AsyncAddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::AddTaskResponse>>(AsyncAddTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::AddTaskResponse>> PrepareAsyncAddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::AddTaskResponse>>(PrepareAsyncAddTaskRaw(context, request, cq));
    }
    virtual ::grpc::Status GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::bi::GetTasksResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetTasksResponse>> AsyncGetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetTasksResponse>>(AsyncGetTasksRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetTasksResponse>> PrepareAsyncGetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetTasksResponse>>(PrepareAsyncGetTasksRaw(context, request, cq));
    }
    virtual ::grpc::Status UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::bi::UpdateTaskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::UpdateTaskResponse>> AsyncUpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::UpdateTaskResponse>>(AsyncUpdateTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::UpdateTaskResponse>> PrepareAsyncUpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::UpdateTaskResponse>>(PrepareAsyncUpdateTaskRaw(context, request, cq));
    }
    virtual ::grpc::Status DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::bi::DeleteTaskResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteTaskResponse>> AsyncDeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteTaskResponse>>(AsyncDeleteTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteTaskResponse>> PrepareAsyncDeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteTaskResponse>>(PrepareAsyncDeleteTaskRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::GenerateReportResponse>* AsyncGenerateReportRaw(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::GenerateReportResponse>* PrepareAsyncGenerateReportRaw(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::ExportReportResponse>* AsyncExportReportRaw(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::ExportReportResponse>* PrepareAsyncExportReportRaw(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetReportsResponse>* AsyncGetReportsRaw(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetReportsResponse>* PrepareAsyncGetReportsRaw(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::ReportResult>* AsyncGetReportRaw(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::ReportResult>* PrepareAsyncGetReportRaw(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteReportResponse>* AsyncDeleteReportRaw(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteReportResponse>* PrepareAsyncDeleteReportRaw(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::AddTaskResponse>* AsyncAddTaskRaw(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::AddTaskResponse>* PrepareAsyncAddTaskRaw(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetTasksResponse>* AsyncGetTasksRaw(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::GetTasksResponse>* PrepareAsyncGetTasksRaw(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::UpdateTaskResponse>* AsyncUpdateTaskRaw(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::UpdateTaskResponse>* PrepareAsyncUpdateTaskRaw(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteTaskResponse>* AsyncDeleteTaskRaw(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bi::DeleteTaskResponse>* PrepareAsyncDeleteTaskRaw(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::bi::GenerateReportResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>> AsyncGenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>>(AsyncGenerateReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>> PrepareAsyncGenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>>(PrepareAsyncGenerateReportRaw(context, request, cq));
    }
    ::grpc::Status ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::bi::ExportReportResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>> AsyncExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>>(AsyncExportReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>> PrepareAsyncExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>>(PrepareAsyncExportReportRaw(context, request, cq));
    }
    ::grpc::Status GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::bi::GetReportsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>> AsyncGetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>>(AsyncGetReportsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>> PrepareAsyncGetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>>(PrepareAsyncGetReportsRaw(context, request, cq));
    }
    ::grpc::Status GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::bi::ReportResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ReportResult>> AsyncGetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ReportResult>>(AsyncGetReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ReportResult>> PrepareAsyncGetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::ReportResult>>(PrepareAsyncGetReportRaw(context, request, cq));
    }
    ::grpc::Status DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::bi::DeleteReportResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>> AsyncDeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>>(AsyncDeleteReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>> PrepareAsyncDeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>>(PrepareAsyncDeleteReportRaw(context, request, cq));
    }
    ::grpc::Status AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::bi::AddTaskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>> AsyncAddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>>(AsyncAddTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>> PrepareAsyncAddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>>(PrepareAsyncAddTaskRaw(context, request, cq));
    }
    ::grpc::Status GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::bi::GetTasksResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>> AsyncGetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>>(AsyncGetTasksRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>> PrepareAsyncGetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>>(PrepareAsyncGetTasksRaw(context, request, cq));
    }
    ::grpc::Status UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::bi::UpdateTaskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>> AsyncUpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>>(AsyncUpdateTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>> PrepareAsyncUpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>>(PrepareAsyncUpdateTaskRaw(context, request, cq));
    }
    ::grpc::Status DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::bi::DeleteTaskResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>> AsyncDeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>>(AsyncDeleteTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>> PrepareAsyncDeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>>(PrepareAsyncDeleteTaskRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response, std::function<void(::grpc::Status)>) override;
      void GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response, std::function<void(::grpc::Status)>) override;
      void ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response, std::function<void(::grpc::Status)>) override;
      void GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response, std::function<void(::grpc::Status)>) override;
      void DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response, std::function<void(::grpc::Status)>) override;
      void AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response, std::function<void(::grpc::Status)>) override;
      void GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response, std::function<void(::grpc::Status)>) override;
      void DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>* AsyncGenerateReportRaw(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>* PrepareAsyncGenerateReportRaw(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>* AsyncExportReportRaw(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>* PrepareAsyncExportReportRaw(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>* AsyncGetReportsRaw(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>* PrepareAsyncGetReportsRaw(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::ReportResult>* AsyncGetReportRaw(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::ReportResult>* PrepareAsyncGetReportRaw(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>* AsyncDeleteReportRaw(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>* PrepareAsyncDeleteReportRaw(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>* AsyncAddTaskRaw(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>* PrepareAsyncAddTaskRaw(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>* AsyncGetTasksRaw(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>* PrepareAsyncGetTasksRaw(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>* AsyncUpdateTaskRaw(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>* PrepareAsyncUpdateTaskRaw(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>* AsyncDeleteTaskRaw(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>* PrepareAsyncDeleteTaskRaw(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GenerateReport_;
    const ::grpc::internal::RpcMethod rpcmethod_ExportReport_;
    const ::grpc::internal::RpcMethod rpcmethod_GetReports_;
    const ::grpc::internal::RpcMethod rpcmethod_GetReport_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteReport_;
    const ::grpc::internal::RpcMethod rpcmethod_AddTask_;
    const ::grpc::internal::RpcMethod rpcmethod_GetTasks_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateTask_;
    const ::grpc::internal::RpcMethod rpcmethod_DeleteTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GenerateReport(::grpc::ServerContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response);
    virtual ::grpc::Status ExportReport(::grpc::ServerContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response);
    virtual ::grpc::Status GetReports(::grpc::ServerContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response);
    virtual ::grpc::Status GetReport(::grpc::ServerContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response);
    virtual ::grpc::Status DeleteReport(::grpc::ServerContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response);
    virtual ::grpc::Status AddTask(::grpc::ServerContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response);
    virtual ::grpc::Status GetTasks(::grpc::ServerContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response);
    virtual ::grpc::Status UpdateTask(::grpc::ServerContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response);
    virtual ::grpc::Status DeleteTask(::grpc::ServerContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GenerateReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GenerateReport() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GenerateReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateReport(::grpc::ServerContext* /*context*/, const ::bi::GenerateReportRequest* /*request*/, ::bi::GenerateReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateReport(::grpc::ServerContext* context, ::bi::GenerateReportRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::GenerateReportResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExportReport() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportReport(::grpc::ServerContext* /*context*/, const ::bi::ExportReportRequest* /*request*/, ::bi::ExportReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExportReport(::grpc::ServerContext* context, ::bi::ExportReportRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::ExportReportResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetReports : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetReports() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetReports() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReports(::grpc::ServerContext* /*context*/, const ::bi::GetReportsRequest* /*request*/, ::bi::GetReportsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReports(::grpc::ServerContext* context, ::bi::GetReportsRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::GetReportsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetReport() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReport(::grpc::ServerContext* /*context*/, const ::bi::GetReportRequest* /*request*/, ::bi::ReportResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReport(::grpc::ServerContext* context, ::bi::GetReportRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::ReportResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteReport() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_DeleteReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteReport(::grpc::ServerContext* /*context*/, const ::bi::DeleteReportRequest* /*request*/, ::bi::DeleteReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteReport(::grpc::ServerContext* context, ::bi::DeleteReportRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::DeleteReportResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddTask() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_AddTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddTask(::grpc::ServerContext* /*context*/, const ::bi::AddTaskRequest* /*request*/, ::bi::AddTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddTask(::grpc::ServerContext* context, ::bi::AddTaskRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::AddTaskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetTasks() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_GetTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTasks(::grpc::ServerContext* /*context*/, const ::bi::GetTasksRequest* /*request*/, ::bi::GetTasksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTasks(::grpc::ServerContext* context, ::bi::GetTasksRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::GetTasksResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateTask() {
      ::grpc::Service::MarkMethodAsync(7);
    }
    ~WithAsyncMethod_UpdateTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateTask(::grpc::ServerContext* /*context*/, const ::bi::UpdateTaskRequest* /*request*/, ::bi::UpdateTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateTask(::grpc::ServerContext* context, ::bi::UpdateTaskRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::UpdateTaskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_DeleteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DeleteTask() {
      ::grpc::Service::MarkMethodAsync(8);
    }
    ~WithAsyncMethod_DeleteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteTask(::grpc::ServerContext* /*context*/, const ::bi::DeleteTaskRequest* /*request*/, ::bi::DeleteTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteTask(::grpc::ServerContext* context, ::bi::DeleteTaskRequest* request, ::grpc::ServerAsyncResponseWriter< ::bi::DeleteTaskResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GenerateReport<WithAsyncMethod_ExportReport<WithAsyncMethod_GetReports<WithAsyncMethod_GetReport<WithAsyncMethod_DeleteReport<WithAsyncMethod_AddTask<WithAsyncMethod_GetTasks<WithAsyncMethod_UpdateTask<WithAsyncMethod_DeleteTask<Service > > > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GenerateReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GenerateReport() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::GenerateReportRequest, ::bi::GenerateReportResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response) { return this->GenerateReport(context, request, response); }));}
    void SetMessageAllocatorFor_GenerateReport(
        ::grpc::MessageAllocator< ::bi::GenerateReportRequest, ::bi::GenerateReportResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::GenerateReportRequest, ::bi::GenerateReportResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GenerateReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateReport(::grpc::ServerContext* /*context*/, const ::bi::GenerateReportRequest* /*request*/, ::bi::GenerateReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenerateReport(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::GenerateReportRequest* /*request*/, ::bi::GenerateReportResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExportReport() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::ExportReportRequest, ::bi::ExportReportResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response) { return this->ExportReport(context, request, response); }));}
    void SetMessageAllocatorFor_ExportReport(
        ::grpc::MessageAllocator< ::bi::ExportReportRequest, ::bi::ExportReportResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::ExportReportRequest, ::bi::ExportReportResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportReport(::grpc::ServerContext* /*context*/, const ::bi::ExportReportRequest* /*request*/, ::bi::ExportReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExportReport(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::ExportReportRequest* /*request*/, ::bi::ExportReportResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetReports : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetReports() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::GetReportsRequest, ::bi::GetReportsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response) { return this->GetReports(context, request, response); }));}
    void SetMessageAllocatorFor_GetReports(
        ::grpc::MessageAllocator< ::bi::GetReportsRequest, ::bi::GetReportsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::GetReportsRequest, ::bi::GetReportsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetReports() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReports(::grpc::ServerContext* /*context*/, const ::bi::GetReportsRequest* /*request*/, ::bi::GetReportsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReports(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::GetReportsRequest* /*request*/, ::bi::GetReportsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetReport() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::GetReportRequest, ::bi::ReportResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response) { return this->GetReport(context, request, response); }));}
    void SetMessageAllocatorFor_GetReport(
        ::grpc::MessageAllocator< ::bi::GetReportRequest, ::bi::ReportResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::GetReportRequest, ::bi::ReportResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReport(::grpc::ServerContext* /*context*/, const ::bi::GetReportRequest* /*request*/, ::bi::ReportResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReport(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::GetReportRequest* /*request*/, ::bi::ReportResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteReport() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::DeleteReportRequest, ::bi::DeleteReportResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response) { return this->DeleteReport(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteReport(
        ::grpc::MessageAllocator< ::bi::DeleteReportRequest, ::bi::DeleteReportResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::DeleteReportRequest, ::bi::DeleteReportResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteReport(::grpc::ServerContext* /*context*/, const ::bi::DeleteReportRequest* /*request*/, ::bi::DeleteReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteReport(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::DeleteReportRequest* /*request*/, ::bi::DeleteReportResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AddTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddTask() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::AddTaskRequest, ::bi::AddTaskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response) { return this->AddTask(context, request, response); }));}
    void SetMessageAllocatorFor_AddTask(
        ::grpc::MessageAllocator< ::bi::AddTaskRequest, ::bi::AddTaskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(5);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::AddTaskRequest, ::bi::AddTaskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddTask(::grpc::ServerContext* /*context*/, const ::bi::AddTaskRequest* /*request*/, ::bi::AddTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddTask(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::AddTaskRequest* /*request*/, ::bi::AddTaskResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetTasks() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::GetTasksRequest, ::bi::GetTasksResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response) { return this->GetTasks(context, request, response); }));}
    void SetMessageAllocatorFor_GetTasks(
        ::grpc::MessageAllocator< ::bi::GetTasksRequest, ::bi::GetTasksResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::GetTasksRequest, ::bi::GetTasksResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTasks(::grpc::ServerContext* /*context*/, const ::bi::GetTasksRequest* /*request*/, ::bi::GetTasksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTasks(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::GetTasksRequest* /*request*/, ::bi::GetTasksResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateTask() {
      ::grpc::Service::MarkMethodCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response) { return this->UpdateTask(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateTask(
        ::grpc::MessageAllocator< ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(7);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateTask(::grpc::ServerContext* /*context*/, const ::bi::UpdateTaskRequest* /*request*/, ::bi::UpdateTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateTask(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::UpdateTaskRequest* /*request*/, ::bi::UpdateTaskResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_DeleteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DeleteTask() {
      ::grpc::Service::MarkMethodCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response) { return this->DeleteTask(context, request, response); }));}
    void SetMessageAllocatorFor_DeleteTask(
        ::grpc::MessageAllocator< ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(8);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DeleteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteTask(::grpc::ServerContext* /*context*/, const ::bi::DeleteTaskRequest* /*request*/, ::bi::DeleteTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteTask(
      ::grpc::CallbackServerContext* /*context*/, const ::bi::DeleteTaskRequest* /*request*/, ::bi::DeleteTaskResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GenerateReport<WithCallbackMethod_ExportReport<WithCallbackMethod_GetReports<WithCallbackMethod_GetReport<WithCallbackMethod_DeleteReport<WithCallbackMethod_AddTask<WithCallbackMethod_GetTasks<WithCallbackMethod_UpdateTask<WithCallbackMethod_DeleteTask<Service > > > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GenerateReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GenerateReport() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GenerateReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateReport(::grpc::ServerContext* /*context*/, const ::bi::GenerateReportRequest* /*request*/, ::bi::GenerateReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExportReport() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportReport(::grpc::ServerContext* /*context*/, const ::bi::ExportReportRequest* /*request*/, ::bi::ExportReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetReports : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetReports() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetReports() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReports(::grpc::ServerContext* /*context*/, const ::bi::GetReportsRequest* /*request*/, ::bi::GetReportsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetReport() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReport(::grpc::ServerContext* /*context*/, const ::bi::GetReportRequest* /*request*/, ::bi::ReportResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteReport() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_DeleteReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteReport(::grpc::ServerContext* /*context*/, const ::bi::DeleteReportRequest* /*request*/, ::bi::DeleteReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddTask() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_AddTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddTask(::grpc::ServerContext* /*context*/, const ::bi::AddTaskRequest* /*request*/, ::bi::AddTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetTasks() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_GetTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTasks(::grpc::ServerContext* /*context*/, const ::bi::GetTasksRequest* /*request*/, ::bi::GetTasksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateTask() {
      ::grpc::Service::MarkMethodGeneric(7);
    }
    ~WithGenericMethod_UpdateTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateTask(::grpc::ServerContext* /*context*/, const ::bi::UpdateTaskRequest* /*request*/, ::bi::UpdateTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_DeleteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DeleteTask() {
      ::grpc::Service::MarkMethodGeneric(8);
    }
    ~WithGenericMethod_DeleteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteTask(::grpc::ServerContext* /*context*/, const ::bi::DeleteTaskRequest* /*request*/, ::bi::DeleteTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GenerateReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GenerateReport() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GenerateReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateReport(::grpc::ServerContext* /*context*/, const ::bi::GenerateReportRequest* /*request*/, ::bi::GenerateReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGenerateReport(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExportReport() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportReport(::grpc::ServerContext* /*context*/, const ::bi::ExportReportRequest* /*request*/, ::bi::ExportReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExportReport(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetReports : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetReports() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetReports() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReports(::grpc::ServerContext* /*context*/, const ::bi::GetReportsRequest* /*request*/, ::bi::GetReportsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReports(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetReport() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReport(::grpc::ServerContext* /*context*/, const ::bi::GetReportRequest* /*request*/, ::bi::ReportResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetReport(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteReport() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_DeleteReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteReport(::grpc::ServerContext* /*context*/, const ::bi::DeleteReportRequest* /*request*/, ::bi::DeleteReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteReport(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddTask() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_AddTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddTask(::grpc::ServerContext* /*context*/, const ::bi::AddTaskRequest* /*request*/, ::bi::AddTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetTasks() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_GetTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTasks(::grpc::ServerContext* /*context*/, const ::bi::GetTasksRequest* /*request*/, ::bi::GetTasksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTasks(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateTask() {
      ::grpc::Service::MarkMethodRaw(7);
    }
    ~WithRawMethod_UpdateTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateTask(::grpc::ServerContext* /*context*/, const ::bi::UpdateTaskRequest* /*request*/, ::bi::UpdateTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_DeleteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DeleteTask() {
      ::grpc::Service::MarkMethodRaw(8);
    }
    ~WithRawMethod_DeleteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteTask(::grpc::ServerContext* /*context*/, const ::bi::DeleteTaskRequest* /*request*/, ::bi::DeleteTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDeleteTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(8, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GenerateReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GenerateReport() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GenerateReport(context, request, response); }));
    }
    ~WithRawCallbackMethod_GenerateReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GenerateReport(::grpc::ServerContext* /*context*/, const ::bi::GenerateReportRequest* /*request*/, ::bi::GenerateReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GenerateReport(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExportReport() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExportReport(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportReport(::grpc::ServerContext* /*context*/, const ::bi::ExportReportRequest* /*request*/, ::bi::ExportReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExportReport(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetReports : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetReports() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetReports(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetReports() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReports(::grpc::ServerContext* /*context*/, const ::bi::GetReportsRequest* /*request*/, ::bi::GetReportsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReports(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetReport() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetReport(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetReport(::grpc::ServerContext* /*context*/, const ::bi::GetReportRequest* /*request*/, ::bi::ReportResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetReport(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteReport() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteReport(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteReport(::grpc::ServerContext* /*context*/, const ::bi::DeleteReportRequest* /*request*/, ::bi::DeleteReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteReport(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddTask() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddTask(::grpc::ServerContext* /*context*/, const ::bi::AddTaskRequest* /*request*/, ::bi::AddTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetTasks() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetTasks(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTasks(::grpc::ServerContext* /*context*/, const ::bi::GetTasksRequest* /*request*/, ::bi::GetTasksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTasks(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateTask() {
      ::grpc::Service::MarkMethodRawCallback(7,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateTask(::grpc::ServerContext* /*context*/, const ::bi::UpdateTaskRequest* /*request*/, ::bi::UpdateTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DeleteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DeleteTask() {
      ::grpc::Service::MarkMethodRawCallback(8,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DeleteTask(context, request, response); }));
    }
    ~WithRawCallbackMethod_DeleteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DeleteTask(::grpc::ServerContext* /*context*/, const ::bi::DeleteTaskRequest* /*request*/, ::bi::DeleteTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DeleteTask(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GenerateReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GenerateReport() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::GenerateReportRequest, ::bi::GenerateReportResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::GenerateReportRequest, ::bi::GenerateReportResponse>* streamer) {
                       return this->StreamedGenerateReport(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GenerateReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GenerateReport(::grpc::ServerContext* /*context*/, const ::bi::GenerateReportRequest* /*request*/, ::bi::GenerateReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGenerateReport(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::GenerateReportRequest,::bi::GenerateReportResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExportReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExportReport() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::ExportReportRequest, ::bi::ExportReportResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::ExportReportRequest, ::bi::ExportReportResponse>* streamer) {
                       return this->StreamedExportReport(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExportReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExportReport(::grpc::ServerContext* /*context*/, const ::bi::ExportReportRequest* /*request*/, ::bi::ExportReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExportReport(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::ExportReportRequest,::bi::ExportReportResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetReports : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetReports() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::GetReportsRequest, ::bi::GetReportsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::GetReportsRequest, ::bi::GetReportsResponse>* streamer) {
                       return this->StreamedGetReports(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetReports() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetReports(::grpc::ServerContext* /*context*/, const ::bi::GetReportsRequest* /*request*/, ::bi::GetReportsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetReports(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::GetReportsRequest,::bi::GetReportsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetReport() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::GetReportRequest, ::bi::ReportResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::GetReportRequest, ::bi::ReportResult>* streamer) {
                       return this->StreamedGetReport(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetReport(::grpc::ServerContext* /*context*/, const ::bi::GetReportRequest* /*request*/, ::bi::ReportResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetReport(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::GetReportRequest,::bi::ReportResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteReport() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::DeleteReportRequest, ::bi::DeleteReportResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::DeleteReportRequest, ::bi::DeleteReportResponse>* streamer) {
                       return this->StreamedDeleteReport(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteReport(::grpc::ServerContext* /*context*/, const ::bi::DeleteReportRequest* /*request*/, ::bi::DeleteReportResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteReport(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::DeleteReportRequest,::bi::DeleteReportResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddTask() {
      ::grpc::Service::MarkMethodStreamed(5,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::AddTaskRequest, ::bi::AddTaskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::AddTaskRequest, ::bi::AddTaskResponse>* streamer) {
                       return this->StreamedAddTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddTask(::grpc::ServerContext* /*context*/, const ::bi::AddTaskRequest* /*request*/, ::bi::AddTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::AddTaskRequest,::bi::AddTaskResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetTasks() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::GetTasksRequest, ::bi::GetTasksResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::GetTasksRequest, ::bi::GetTasksResponse>* streamer) {
                       return this->StreamedGetTasks(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTasks(::grpc::ServerContext* /*context*/, const ::bi::GetTasksRequest* /*request*/, ::bi::GetTasksResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetTasks(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::GetTasksRequest,::bi::GetTasksResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateTask() {
      ::grpc::Service::MarkMethodStreamed(7,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse>* streamer) {
                       return this->StreamedUpdateTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateTask(::grpc::ServerContext* /*context*/, const ::bi::UpdateTaskRequest* /*request*/, ::bi::UpdateTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::UpdateTaskRequest,::bi::UpdateTaskResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DeleteTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DeleteTask() {
      ::grpc::Service::MarkMethodStreamed(8,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse>* streamer) {
                       return this->StreamedDeleteTask(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DeleteTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DeleteTask(::grpc::ServerContext* /*context*/, const ::bi::DeleteTaskRequest* /*request*/, ::bi::DeleteTaskResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDeleteTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bi::DeleteTaskRequest,::bi::DeleteTaskResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GenerateReport<WithStreamedUnaryMethod_ExportReport<WithStreamedUnaryMethod_GetReports<WithStreamedUnaryMethod_GetReport<WithStreamedUnaryMethod_DeleteReport<WithStreamedUnaryMethod_AddTask<WithStreamedUnaryMethod_GetTasks<WithStreamedUnaryMethod_UpdateTask<WithStreamedUnaryMethod_DeleteTask<Service > > > > > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GenerateReport<WithStreamedUnaryMethod_ExportReport<WithStreamedUnaryMethod_GetReports<WithStreamedUnaryMethod_GetReport<WithStreamedUnaryMethod_DeleteReport<WithStreamedUnaryMethod_AddTask<WithStreamedUnaryMethod_GetTasks<WithStreamedUnaryMethod_UpdateTask<WithStreamedUnaryMethod_DeleteTask<Service > > > > > > > > > StreamedService;
};

}  // namespace bi


#endif  // GRPC_bi_2eproto__INCLUDED
