// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: decision.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_decision_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_decision_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_decision_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_decision_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_decision_2eproto;
namespace decision {
class Decision;
struct DecisionDefaultTypeInternal;
extern DecisionDefaultTypeInternal _Decision_default_instance_;
class GetDecisionsRequest;
struct GetDecisionsRequestDefaultTypeInternal;
extern GetDecisionsRequestDefaultTypeInternal _GetDecisionsRequest_default_instance_;
class GetDecisionsResponse;
struct GetDecisionsResponseDefaultTypeInternal;
extern GetDecisionsResponseDefaultTypeInternal _GetDecisionsResponse_default_instance_;
class ReportDecisionRequest;
struct ReportDecisionRequestDefaultTypeInternal;
extern ReportDecisionRequestDefaultTypeInternal _ReportDecisionRequest_default_instance_;
class ReportDecisionResponse;
struct ReportDecisionResponseDefaultTypeInternal;
extern ReportDecisionResponseDefaultTypeInternal _ReportDecisionResponse_default_instance_;
}  // namespace decision
PROTOBUF_NAMESPACE_OPEN
template<> ::decision::Decision* Arena::CreateMaybeMessage<::decision::Decision>(Arena*);
template<> ::decision::GetDecisionsRequest* Arena::CreateMaybeMessage<::decision::GetDecisionsRequest>(Arena*);
template<> ::decision::GetDecisionsResponse* Arena::CreateMaybeMessage<::decision::GetDecisionsResponse>(Arena*);
template<> ::decision::ReportDecisionRequest* Arena::CreateMaybeMessage<::decision::ReportDecisionRequest>(Arena*);
template<> ::decision::ReportDecisionResponse* Arena::CreateMaybeMessage<::decision::ReportDecisionResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace decision {

// ===================================================================

class Decision final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:decision.Decision) */ {
 public:
  inline Decision() : Decision(nullptr) {}
  ~Decision() override;
  explicit PROTOBUF_CONSTEXPR Decision(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Decision(const Decision& from);
  Decision(Decision&& from) noexcept
    : Decision() {
    *this = ::std::move(from);
  }

  inline Decision& operator=(const Decision& from) {
    CopyFrom(from);
    return *this;
  }
  inline Decision& operator=(Decision&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Decision& default_instance() {
    return *internal_default_instance();
  }
  static inline const Decision* internal_default_instance() {
    return reinterpret_cast<const Decision*>(
               &_Decision_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Decision& a, Decision& b) {
    a.Swap(&b);
  }
  inline void Swap(Decision* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Decision* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Decision* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Decision>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Decision& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Decision& from) {
    Decision::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Decision* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "decision.Decision";
  }
  protected:
  explicit Decision(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAssetNameFieldNumber = 2,
    kLocationFieldNumber = 3,
    kActionFieldNumber = 4,
    kRiskLevelFieldNumber = 5,
    kReasonFieldNumber = 6,
    kTimestampFieldNumber = 7,
    kAssetIdFieldNumber = 1,
    kIsHandledFieldNumber = 8,
    kIsExecutedFieldNumber = 9,
    kIsIgnoredFieldNumber = 10,
  };
  // string asset_name = 2;
  void clear_asset_name();
  const std::string& asset_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_asset_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_asset_name();
  PROTOBUF_NODISCARD std::string* release_asset_name();
  void set_allocated_asset_name(std::string* asset_name);
  private:
  const std::string& _internal_asset_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_asset_name(const std::string& value);
  std::string* _internal_mutable_asset_name();
  public:

  // string location = 3;
  void clear_location();
  const std::string& location() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_location(ArgT0&& arg0, ArgT... args);
  std::string* mutable_location();
  PROTOBUF_NODISCARD std::string* release_location();
  void set_allocated_location(std::string* location);
  private:
  const std::string& _internal_location() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_location(const std::string& value);
  std::string* _internal_mutable_location();
  public:

  // string action = 4;
  void clear_action();
  const std::string& action() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_action(ArgT0&& arg0, ArgT... args);
  std::string* mutable_action();
  PROTOBUF_NODISCARD std::string* release_action();
  void set_allocated_action(std::string* action);
  private:
  const std::string& _internal_action() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_action(const std::string& value);
  std::string* _internal_mutable_action();
  public:

  // string risk_level = 5;
  void clear_risk_level();
  const std::string& risk_level() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_risk_level(ArgT0&& arg0, ArgT... args);
  std::string* mutable_risk_level();
  PROTOBUF_NODISCARD std::string* release_risk_level();
  void set_allocated_risk_level(std::string* risk_level);
  private:
  const std::string& _internal_risk_level() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_risk_level(const std::string& value);
  std::string* _internal_mutable_risk_level();
  public:

  // string reason = 6;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // string timestamp = 7;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // int32 asset_id = 1;
  void clear_asset_id();
  int32_t asset_id() const;
  void set_asset_id(int32_t value);
  private:
  int32_t _internal_asset_id() const;
  void _internal_set_asset_id(int32_t value);
  public:

  // bool is_handled = 8;
  void clear_is_handled();
  bool is_handled() const;
  void set_is_handled(bool value);
  private:
  bool _internal_is_handled() const;
  void _internal_set_is_handled(bool value);
  public:

  // bool is_executed = 9;
  void clear_is_executed();
  bool is_executed() const;
  void set_is_executed(bool value);
  private:
  bool _internal_is_executed() const;
  void _internal_set_is_executed(bool value);
  public:

  // bool is_ignored = 10;
  void clear_is_ignored();
  bool is_ignored() const;
  void set_is_ignored(bool value);
  private:
  bool _internal_is_ignored() const;
  void _internal_set_is_ignored(bool value);
  public:

  // @@protoc_insertion_point(class_scope:decision.Decision)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr asset_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr location_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr risk_level_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    int32_t asset_id_;
    bool is_handled_;
    bool is_executed_;
    bool is_ignored_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_decision_2eproto;
};
// -------------------------------------------------------------------

class GetDecisionsRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:decision.GetDecisionsRequest) */ {
 public:
  inline GetDecisionsRequest() : GetDecisionsRequest(nullptr) {}
  ~GetDecisionsRequest() override;
  explicit PROTOBUF_CONSTEXPR GetDecisionsRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetDecisionsRequest(const GetDecisionsRequest& from);
  GetDecisionsRequest(GetDecisionsRequest&& from) noexcept
    : GetDecisionsRequest() {
    *this = ::std::move(from);
  }

  inline GetDecisionsRequest& operator=(const GetDecisionsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDecisionsRequest& operator=(GetDecisionsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDecisionsRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetDecisionsRequest* internal_default_instance() {
    return reinterpret_cast<const GetDecisionsRequest*>(
               &_GetDecisionsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetDecisionsRequest& a, GetDecisionsRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetDecisionsRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDecisionsRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDecisionsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetDecisionsRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetDecisionsRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetDecisionsRequest& from) {
    GetDecisionsRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDecisionsRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "decision.GetDecisionsRequest";
  }
  protected:
  explicit GetDecisionsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserFilterFieldNumber = 2,
    kLimitFieldNumber = 1,
  };
  // string user_filter = 2;
  void clear_user_filter();
  const std::string& user_filter() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user_filter(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user_filter();
  PROTOBUF_NODISCARD std::string* release_user_filter();
  void set_allocated_user_filter(std::string* user_filter);
  private:
  const std::string& _internal_user_filter() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user_filter(const std::string& value);
  std::string* _internal_mutable_user_filter();
  public:

  // int32 limit = 1;
  void clear_limit();
  int32_t limit() const;
  void set_limit(int32_t value);
  private:
  int32_t _internal_limit() const;
  void _internal_set_limit(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:decision.GetDecisionsRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_filter_;
    int32_t limit_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_decision_2eproto;
};
// -------------------------------------------------------------------

class GetDecisionsResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:decision.GetDecisionsResponse) */ {
 public:
  inline GetDecisionsResponse() : GetDecisionsResponse(nullptr) {}
  ~GetDecisionsResponse() override;
  explicit PROTOBUF_CONSTEXPR GetDecisionsResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetDecisionsResponse(const GetDecisionsResponse& from);
  GetDecisionsResponse(GetDecisionsResponse&& from) noexcept
    : GetDecisionsResponse() {
    *this = ::std::move(from);
  }

  inline GetDecisionsResponse& operator=(const GetDecisionsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDecisionsResponse& operator=(GetDecisionsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDecisionsResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetDecisionsResponse* internal_default_instance() {
    return reinterpret_cast<const GetDecisionsResponse*>(
               &_GetDecisionsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetDecisionsResponse& a, GetDecisionsResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetDecisionsResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDecisionsResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDecisionsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetDecisionsResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetDecisionsResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetDecisionsResponse& from) {
    GetDecisionsResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetDecisionsResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "decision.GetDecisionsResponse";
  }
  protected:
  explicit GetDecisionsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDecisionsFieldNumber = 1,
    kAdoptionRateFieldNumber = 3,
    kTotalCountFieldNumber = 2,
  };
  // repeated .decision.Decision decisions = 1;
  int decisions_size() const;
  private:
  int _internal_decisions_size() const;
  public:
  void clear_decisions();
  ::decision::Decision* mutable_decisions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::decision::Decision >*
      mutable_decisions();
  private:
  const ::decision::Decision& _internal_decisions(int index) const;
  ::decision::Decision* _internal_add_decisions();
  public:
  const ::decision::Decision& decisions(int index) const;
  ::decision::Decision* add_decisions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::decision::Decision >&
      decisions() const;

  // double adoption_rate = 3;
  void clear_adoption_rate();
  double adoption_rate() const;
  void set_adoption_rate(double value);
  private:
  double _internal_adoption_rate() const;
  void _internal_set_adoption_rate(double value);
  public:

  // int32 total_count = 2;
  void clear_total_count();
  int32_t total_count() const;
  void set_total_count(int32_t value);
  private:
  int32_t _internal_total_count() const;
  void _internal_set_total_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:decision.GetDecisionsResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::decision::Decision > decisions_;
    double adoption_rate_;
    int32_t total_count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_decision_2eproto;
};
// -------------------------------------------------------------------

class ReportDecisionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:decision.ReportDecisionRequest) */ {
 public:
  inline ReportDecisionRequest() : ReportDecisionRequest(nullptr) {}
  ~ReportDecisionRequest() override;
  explicit PROTOBUF_CONSTEXPR ReportDecisionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReportDecisionRequest(const ReportDecisionRequest& from);
  ReportDecisionRequest(ReportDecisionRequest&& from) noexcept
    : ReportDecisionRequest() {
    *this = ::std::move(from);
  }

  inline ReportDecisionRequest& operator=(const ReportDecisionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReportDecisionRequest& operator=(ReportDecisionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReportDecisionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReportDecisionRequest* internal_default_instance() {
    return reinterpret_cast<const ReportDecisionRequest*>(
               &_ReportDecisionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ReportDecisionRequest& a, ReportDecisionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReportDecisionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReportDecisionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReportDecisionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReportDecisionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReportDecisionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReportDecisionRequest& from) {
    ReportDecisionRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReportDecisionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "decision.ReportDecisionRequest";
  }
  protected:
  explicit ReportDecisionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOperatorNameFieldNumber = 4,
    kAssetIdFieldNumber = 1,
    kExecutedFieldNumber = 2,
    kIgnoredFieldNumber = 3,
  };
  // string operator_name = 4;
  void clear_operator_name();
  const std::string& operator_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_operator_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_operator_name();
  PROTOBUF_NODISCARD std::string* release_operator_name();
  void set_allocated_operator_name(std::string* operator_name);
  private:
  const std::string& _internal_operator_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_operator_name(const std::string& value);
  std::string* _internal_mutable_operator_name();
  public:

  // int32 asset_id = 1;
  void clear_asset_id();
  int32_t asset_id() const;
  void set_asset_id(int32_t value);
  private:
  int32_t _internal_asset_id() const;
  void _internal_set_asset_id(int32_t value);
  public:

  // bool executed = 2;
  void clear_executed();
  bool executed() const;
  void set_executed(bool value);
  private:
  bool _internal_executed() const;
  void _internal_set_executed(bool value);
  public:

  // bool ignored = 3;
  void clear_ignored();
  bool ignored() const;
  void set_ignored(bool value);
  private:
  bool _internal_ignored() const;
  void _internal_set_ignored(bool value);
  public:

  // @@protoc_insertion_point(class_scope:decision.ReportDecisionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr operator_name_;
    int32_t asset_id_;
    bool executed_;
    bool ignored_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_decision_2eproto;
};
// -------------------------------------------------------------------

class ReportDecisionResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:decision.ReportDecisionResponse) */ {
 public:
  inline ReportDecisionResponse() : ReportDecisionResponse(nullptr) {}
  ~ReportDecisionResponse() override;
  explicit PROTOBUF_CONSTEXPR ReportDecisionResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReportDecisionResponse(const ReportDecisionResponse& from);
  ReportDecisionResponse(ReportDecisionResponse&& from) noexcept
    : ReportDecisionResponse() {
    *this = ::std::move(from);
  }

  inline ReportDecisionResponse& operator=(const ReportDecisionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReportDecisionResponse& operator=(ReportDecisionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReportDecisionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReportDecisionResponse* internal_default_instance() {
    return reinterpret_cast<const ReportDecisionResponse*>(
               &_ReportDecisionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ReportDecisionResponse& a, ReportDecisionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ReportDecisionResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReportDecisionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReportDecisionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReportDecisionResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReportDecisionResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReportDecisionResponse& from) {
    ReportDecisionResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReportDecisionResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "decision.ReportDecisionResponse";
  }
  protected:
  explicit ReportDecisionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kSuccessFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool success = 1;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:decision.ReportDecisionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    bool success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_decision_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Decision

// int32 asset_id = 1;
inline void Decision::clear_asset_id() {
  _impl_.asset_id_ = 0;
}
inline int32_t Decision::_internal_asset_id() const {
  return _impl_.asset_id_;
}
inline int32_t Decision::asset_id() const {
  // @@protoc_insertion_point(field_get:decision.Decision.asset_id)
  return _internal_asset_id();
}
inline void Decision::_internal_set_asset_id(int32_t value) {
  
  _impl_.asset_id_ = value;
}
inline void Decision::set_asset_id(int32_t value) {
  _internal_set_asset_id(value);
  // @@protoc_insertion_point(field_set:decision.Decision.asset_id)
}

// string asset_name = 2;
inline void Decision::clear_asset_name() {
  _impl_.asset_name_.ClearToEmpty();
}
inline const std::string& Decision::asset_name() const {
  // @@protoc_insertion_point(field_get:decision.Decision.asset_name)
  return _internal_asset_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Decision::set_asset_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.asset_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.Decision.asset_name)
}
inline std::string* Decision::mutable_asset_name() {
  std::string* _s = _internal_mutable_asset_name();
  // @@protoc_insertion_point(field_mutable:decision.Decision.asset_name)
  return _s;
}
inline const std::string& Decision::_internal_asset_name() const {
  return _impl_.asset_name_.Get();
}
inline void Decision::_internal_set_asset_name(const std::string& value) {
  
  _impl_.asset_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Decision::_internal_mutable_asset_name() {
  
  return _impl_.asset_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Decision::release_asset_name() {
  // @@protoc_insertion_point(field_release:decision.Decision.asset_name)
  return _impl_.asset_name_.Release();
}
inline void Decision::set_allocated_asset_name(std::string* asset_name) {
  if (asset_name != nullptr) {
    
  } else {
    
  }
  _impl_.asset_name_.SetAllocated(asset_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.asset_name_.IsDefault()) {
    _impl_.asset_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.Decision.asset_name)
}

// string location = 3;
inline void Decision::clear_location() {
  _impl_.location_.ClearToEmpty();
}
inline const std::string& Decision::location() const {
  // @@protoc_insertion_point(field_get:decision.Decision.location)
  return _internal_location();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Decision::set_location(ArgT0&& arg0, ArgT... args) {
 
 _impl_.location_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.Decision.location)
}
inline std::string* Decision::mutable_location() {
  std::string* _s = _internal_mutable_location();
  // @@protoc_insertion_point(field_mutable:decision.Decision.location)
  return _s;
}
inline const std::string& Decision::_internal_location() const {
  return _impl_.location_.Get();
}
inline void Decision::_internal_set_location(const std::string& value) {
  
  _impl_.location_.Set(value, GetArenaForAllocation());
}
inline std::string* Decision::_internal_mutable_location() {
  
  return _impl_.location_.Mutable(GetArenaForAllocation());
}
inline std::string* Decision::release_location() {
  // @@protoc_insertion_point(field_release:decision.Decision.location)
  return _impl_.location_.Release();
}
inline void Decision::set_allocated_location(std::string* location) {
  if (location != nullptr) {
    
  } else {
    
  }
  _impl_.location_.SetAllocated(location, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.location_.IsDefault()) {
    _impl_.location_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.Decision.location)
}

// string action = 4;
inline void Decision::clear_action() {
  _impl_.action_.ClearToEmpty();
}
inline const std::string& Decision::action() const {
  // @@protoc_insertion_point(field_get:decision.Decision.action)
  return _internal_action();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Decision::set_action(ArgT0&& arg0, ArgT... args) {
 
 _impl_.action_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.Decision.action)
}
inline std::string* Decision::mutable_action() {
  std::string* _s = _internal_mutable_action();
  // @@protoc_insertion_point(field_mutable:decision.Decision.action)
  return _s;
}
inline const std::string& Decision::_internal_action() const {
  return _impl_.action_.Get();
}
inline void Decision::_internal_set_action(const std::string& value) {
  
  _impl_.action_.Set(value, GetArenaForAllocation());
}
inline std::string* Decision::_internal_mutable_action() {
  
  return _impl_.action_.Mutable(GetArenaForAllocation());
}
inline std::string* Decision::release_action() {
  // @@protoc_insertion_point(field_release:decision.Decision.action)
  return _impl_.action_.Release();
}
inline void Decision::set_allocated_action(std::string* action) {
  if (action != nullptr) {
    
  } else {
    
  }
  _impl_.action_.SetAllocated(action, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.action_.IsDefault()) {
    _impl_.action_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.Decision.action)
}

// string risk_level = 5;
inline void Decision::clear_risk_level() {
  _impl_.risk_level_.ClearToEmpty();
}
inline const std::string& Decision::risk_level() const {
  // @@protoc_insertion_point(field_get:decision.Decision.risk_level)
  return _internal_risk_level();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Decision::set_risk_level(ArgT0&& arg0, ArgT... args) {
 
 _impl_.risk_level_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.Decision.risk_level)
}
inline std::string* Decision::mutable_risk_level() {
  std::string* _s = _internal_mutable_risk_level();
  // @@protoc_insertion_point(field_mutable:decision.Decision.risk_level)
  return _s;
}
inline const std::string& Decision::_internal_risk_level() const {
  return _impl_.risk_level_.Get();
}
inline void Decision::_internal_set_risk_level(const std::string& value) {
  
  _impl_.risk_level_.Set(value, GetArenaForAllocation());
}
inline std::string* Decision::_internal_mutable_risk_level() {
  
  return _impl_.risk_level_.Mutable(GetArenaForAllocation());
}
inline std::string* Decision::release_risk_level() {
  // @@protoc_insertion_point(field_release:decision.Decision.risk_level)
  return _impl_.risk_level_.Release();
}
inline void Decision::set_allocated_risk_level(std::string* risk_level) {
  if (risk_level != nullptr) {
    
  } else {
    
  }
  _impl_.risk_level_.SetAllocated(risk_level, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.risk_level_.IsDefault()) {
    _impl_.risk_level_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.Decision.risk_level)
}

// string reason = 6;
inline void Decision::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& Decision::reason() const {
  // @@protoc_insertion_point(field_get:decision.Decision.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Decision::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.Decision.reason)
}
inline std::string* Decision::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:decision.Decision.reason)
  return _s;
}
inline const std::string& Decision::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void Decision::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* Decision::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* Decision::release_reason() {
  // @@protoc_insertion_point(field_release:decision.Decision.reason)
  return _impl_.reason_.Release();
}
inline void Decision::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.Decision.reason)
}

// string timestamp = 7;
inline void Decision::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& Decision::timestamp() const {
  // @@protoc_insertion_point(field_get:decision.Decision.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Decision::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.Decision.timestamp)
}
inline std::string* Decision::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:decision.Decision.timestamp)
  return _s;
}
inline const std::string& Decision::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void Decision::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* Decision::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* Decision::release_timestamp() {
  // @@protoc_insertion_point(field_release:decision.Decision.timestamp)
  return _impl_.timestamp_.Release();
}
inline void Decision::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.Decision.timestamp)
}

// bool is_handled = 8;
inline void Decision::clear_is_handled() {
  _impl_.is_handled_ = false;
}
inline bool Decision::_internal_is_handled() const {
  return _impl_.is_handled_;
}
inline bool Decision::is_handled() const {
  // @@protoc_insertion_point(field_get:decision.Decision.is_handled)
  return _internal_is_handled();
}
inline void Decision::_internal_set_is_handled(bool value) {
  
  _impl_.is_handled_ = value;
}
inline void Decision::set_is_handled(bool value) {
  _internal_set_is_handled(value);
  // @@protoc_insertion_point(field_set:decision.Decision.is_handled)
}

// bool is_executed = 9;
inline void Decision::clear_is_executed() {
  _impl_.is_executed_ = false;
}
inline bool Decision::_internal_is_executed() const {
  return _impl_.is_executed_;
}
inline bool Decision::is_executed() const {
  // @@protoc_insertion_point(field_get:decision.Decision.is_executed)
  return _internal_is_executed();
}
inline void Decision::_internal_set_is_executed(bool value) {
  
  _impl_.is_executed_ = value;
}
inline void Decision::set_is_executed(bool value) {
  _internal_set_is_executed(value);
  // @@protoc_insertion_point(field_set:decision.Decision.is_executed)
}

// bool is_ignored = 10;
inline void Decision::clear_is_ignored() {
  _impl_.is_ignored_ = false;
}
inline bool Decision::_internal_is_ignored() const {
  return _impl_.is_ignored_;
}
inline bool Decision::is_ignored() const {
  // @@protoc_insertion_point(field_get:decision.Decision.is_ignored)
  return _internal_is_ignored();
}
inline void Decision::_internal_set_is_ignored(bool value) {
  
  _impl_.is_ignored_ = value;
}
inline void Decision::set_is_ignored(bool value) {
  _internal_set_is_ignored(value);
  // @@protoc_insertion_point(field_set:decision.Decision.is_ignored)
}

// -------------------------------------------------------------------

// GetDecisionsRequest

// int32 limit = 1;
inline void GetDecisionsRequest::clear_limit() {
  _impl_.limit_ = 0;
}
inline int32_t GetDecisionsRequest::_internal_limit() const {
  return _impl_.limit_;
}
inline int32_t GetDecisionsRequest::limit() const {
  // @@protoc_insertion_point(field_get:decision.GetDecisionsRequest.limit)
  return _internal_limit();
}
inline void GetDecisionsRequest::_internal_set_limit(int32_t value) {
  
  _impl_.limit_ = value;
}
inline void GetDecisionsRequest::set_limit(int32_t value) {
  _internal_set_limit(value);
  // @@protoc_insertion_point(field_set:decision.GetDecisionsRequest.limit)
}

// string user_filter = 2;
inline void GetDecisionsRequest::clear_user_filter() {
  _impl_.user_filter_.ClearToEmpty();
}
inline const std::string& GetDecisionsRequest::user_filter() const {
  // @@protoc_insertion_point(field_get:decision.GetDecisionsRequest.user_filter)
  return _internal_user_filter();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetDecisionsRequest::set_user_filter(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_filter_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.GetDecisionsRequest.user_filter)
}
inline std::string* GetDecisionsRequest::mutable_user_filter() {
  std::string* _s = _internal_mutable_user_filter();
  // @@protoc_insertion_point(field_mutable:decision.GetDecisionsRequest.user_filter)
  return _s;
}
inline const std::string& GetDecisionsRequest::_internal_user_filter() const {
  return _impl_.user_filter_.Get();
}
inline void GetDecisionsRequest::_internal_set_user_filter(const std::string& value) {
  
  _impl_.user_filter_.Set(value, GetArenaForAllocation());
}
inline std::string* GetDecisionsRequest::_internal_mutable_user_filter() {
  
  return _impl_.user_filter_.Mutable(GetArenaForAllocation());
}
inline std::string* GetDecisionsRequest::release_user_filter() {
  // @@protoc_insertion_point(field_release:decision.GetDecisionsRequest.user_filter)
  return _impl_.user_filter_.Release();
}
inline void GetDecisionsRequest::set_allocated_user_filter(std::string* user_filter) {
  if (user_filter != nullptr) {
    
  } else {
    
  }
  _impl_.user_filter_.SetAllocated(user_filter, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_filter_.IsDefault()) {
    _impl_.user_filter_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.GetDecisionsRequest.user_filter)
}

// -------------------------------------------------------------------

// GetDecisionsResponse

// repeated .decision.Decision decisions = 1;
inline int GetDecisionsResponse::_internal_decisions_size() const {
  return _impl_.decisions_.size();
}
inline int GetDecisionsResponse::decisions_size() const {
  return _internal_decisions_size();
}
inline void GetDecisionsResponse::clear_decisions() {
  _impl_.decisions_.Clear();
}
inline ::decision::Decision* GetDecisionsResponse::mutable_decisions(int index) {
  // @@protoc_insertion_point(field_mutable:decision.GetDecisionsResponse.decisions)
  return _impl_.decisions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::decision::Decision >*
GetDecisionsResponse::mutable_decisions() {
  // @@protoc_insertion_point(field_mutable_list:decision.GetDecisionsResponse.decisions)
  return &_impl_.decisions_;
}
inline const ::decision::Decision& GetDecisionsResponse::_internal_decisions(int index) const {
  return _impl_.decisions_.Get(index);
}
inline const ::decision::Decision& GetDecisionsResponse::decisions(int index) const {
  // @@protoc_insertion_point(field_get:decision.GetDecisionsResponse.decisions)
  return _internal_decisions(index);
}
inline ::decision::Decision* GetDecisionsResponse::_internal_add_decisions() {
  return _impl_.decisions_.Add();
}
inline ::decision::Decision* GetDecisionsResponse::add_decisions() {
  ::decision::Decision* _add = _internal_add_decisions();
  // @@protoc_insertion_point(field_add:decision.GetDecisionsResponse.decisions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::decision::Decision >&
GetDecisionsResponse::decisions() const {
  // @@protoc_insertion_point(field_list:decision.GetDecisionsResponse.decisions)
  return _impl_.decisions_;
}

// int32 total_count = 2;
inline void GetDecisionsResponse::clear_total_count() {
  _impl_.total_count_ = 0;
}
inline int32_t GetDecisionsResponse::_internal_total_count() const {
  return _impl_.total_count_;
}
inline int32_t GetDecisionsResponse::total_count() const {
  // @@protoc_insertion_point(field_get:decision.GetDecisionsResponse.total_count)
  return _internal_total_count();
}
inline void GetDecisionsResponse::_internal_set_total_count(int32_t value) {
  
  _impl_.total_count_ = value;
}
inline void GetDecisionsResponse::set_total_count(int32_t value) {
  _internal_set_total_count(value);
  // @@protoc_insertion_point(field_set:decision.GetDecisionsResponse.total_count)
}

// double adoption_rate = 3;
inline void GetDecisionsResponse::clear_adoption_rate() {
  _impl_.adoption_rate_ = 0;
}
inline double GetDecisionsResponse::_internal_adoption_rate() const {
  return _impl_.adoption_rate_;
}
inline double GetDecisionsResponse::adoption_rate() const {
  // @@protoc_insertion_point(field_get:decision.GetDecisionsResponse.adoption_rate)
  return _internal_adoption_rate();
}
inline void GetDecisionsResponse::_internal_set_adoption_rate(double value) {
  
  _impl_.adoption_rate_ = value;
}
inline void GetDecisionsResponse::set_adoption_rate(double value) {
  _internal_set_adoption_rate(value);
  // @@protoc_insertion_point(field_set:decision.GetDecisionsResponse.adoption_rate)
}

// -------------------------------------------------------------------

// ReportDecisionRequest

// int32 asset_id = 1;
inline void ReportDecisionRequest::clear_asset_id() {
  _impl_.asset_id_ = 0;
}
inline int32_t ReportDecisionRequest::_internal_asset_id() const {
  return _impl_.asset_id_;
}
inline int32_t ReportDecisionRequest::asset_id() const {
  // @@protoc_insertion_point(field_get:decision.ReportDecisionRequest.asset_id)
  return _internal_asset_id();
}
inline void ReportDecisionRequest::_internal_set_asset_id(int32_t value) {
  
  _impl_.asset_id_ = value;
}
inline void ReportDecisionRequest::set_asset_id(int32_t value) {
  _internal_set_asset_id(value);
  // @@protoc_insertion_point(field_set:decision.ReportDecisionRequest.asset_id)
}

// bool executed = 2;
inline void ReportDecisionRequest::clear_executed() {
  _impl_.executed_ = false;
}
inline bool ReportDecisionRequest::_internal_executed() const {
  return _impl_.executed_;
}
inline bool ReportDecisionRequest::executed() const {
  // @@protoc_insertion_point(field_get:decision.ReportDecisionRequest.executed)
  return _internal_executed();
}
inline void ReportDecisionRequest::_internal_set_executed(bool value) {
  
  _impl_.executed_ = value;
}
inline void ReportDecisionRequest::set_executed(bool value) {
  _internal_set_executed(value);
  // @@protoc_insertion_point(field_set:decision.ReportDecisionRequest.executed)
}

// bool ignored = 3;
inline void ReportDecisionRequest::clear_ignored() {
  _impl_.ignored_ = false;
}
inline bool ReportDecisionRequest::_internal_ignored() const {
  return _impl_.ignored_;
}
inline bool ReportDecisionRequest::ignored() const {
  // @@protoc_insertion_point(field_get:decision.ReportDecisionRequest.ignored)
  return _internal_ignored();
}
inline void ReportDecisionRequest::_internal_set_ignored(bool value) {
  
  _impl_.ignored_ = value;
}
inline void ReportDecisionRequest::set_ignored(bool value) {
  _internal_set_ignored(value);
  // @@protoc_insertion_point(field_set:decision.ReportDecisionRequest.ignored)
}

// string operator_name = 4;
inline void ReportDecisionRequest::clear_operator_name() {
  _impl_.operator_name_.ClearToEmpty();
}
inline const std::string& ReportDecisionRequest::operator_name() const {
  // @@protoc_insertion_point(field_get:decision.ReportDecisionRequest.operator_name)
  return _internal_operator_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReportDecisionRequest::set_operator_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.operator_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.ReportDecisionRequest.operator_name)
}
inline std::string* ReportDecisionRequest::mutable_operator_name() {
  std::string* _s = _internal_mutable_operator_name();
  // @@protoc_insertion_point(field_mutable:decision.ReportDecisionRequest.operator_name)
  return _s;
}
inline const std::string& ReportDecisionRequest::_internal_operator_name() const {
  return _impl_.operator_name_.Get();
}
inline void ReportDecisionRequest::_internal_set_operator_name(const std::string& value) {
  
  _impl_.operator_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ReportDecisionRequest::_internal_mutable_operator_name() {
  
  return _impl_.operator_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ReportDecisionRequest::release_operator_name() {
  // @@protoc_insertion_point(field_release:decision.ReportDecisionRequest.operator_name)
  return _impl_.operator_name_.Release();
}
inline void ReportDecisionRequest::set_allocated_operator_name(std::string* operator_name) {
  if (operator_name != nullptr) {
    
  } else {
    
  }
  _impl_.operator_name_.SetAllocated(operator_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.operator_name_.IsDefault()) {
    _impl_.operator_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.ReportDecisionRequest.operator_name)
}

// -------------------------------------------------------------------

// ReportDecisionResponse

// bool success = 1;
inline void ReportDecisionResponse::clear_success() {
  _impl_.success_ = false;
}
inline bool ReportDecisionResponse::_internal_success() const {
  return _impl_.success_;
}
inline bool ReportDecisionResponse::success() const {
  // @@protoc_insertion_point(field_get:decision.ReportDecisionResponse.success)
  return _internal_success();
}
inline void ReportDecisionResponse::_internal_set_success(bool value) {
  
  _impl_.success_ = value;
}
inline void ReportDecisionResponse::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:decision.ReportDecisionResponse.success)
}

// string message = 2;
inline void ReportDecisionResponse::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ReportDecisionResponse::message() const {
  // @@protoc_insertion_point(field_get:decision.ReportDecisionResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ReportDecisionResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:decision.ReportDecisionResponse.message)
}
inline std::string* ReportDecisionResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:decision.ReportDecisionResponse.message)
  return _s;
}
inline const std::string& ReportDecisionResponse::_internal_message() const {
  return _impl_.message_.Get();
}
inline void ReportDecisionResponse::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* ReportDecisionResponse::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* ReportDecisionResponse::release_message() {
  // @@protoc_insertion_point(field_release:decision.ReportDecisionResponse.message)
  return _impl_.message_.Release();
}
inline void ReportDecisionResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:decision.ReportDecisionResponse.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace decision

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_decision_2eproto
