// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: decision.proto

#include "decision.pb.h"
#include "decision.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace decision {

static const char* DecisionService_method_names[] = {
  "/decision.DecisionService/GetDecisions",
  "/decision.DecisionService/ReportDecision",
};

std::unique_ptr< DecisionService::Stub> DecisionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DecisionService::Stub> stub(new DecisionService::Stub(channel, options));
  return stub;
}

DecisionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetDecisions_(DecisionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReportDecision_(DecisionService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DecisionService::Stub::GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::decision::GetDecisionsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDecisions_, context, request, response);
}

void DecisionService::Stub::async::GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDecisions_, context, request, response, std::move(f));
}

void DecisionService::Stub::async::GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDecisions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>* DecisionService::Stub::PrepareAsyncGetDecisionsRaw(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::decision::GetDecisionsResponse, ::decision::GetDecisionsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDecisions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>* DecisionService::Stub::AsyncGetDecisionsRaw(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDecisionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DecisionService::Stub::ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::decision::ReportDecisionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReportDecision_, context, request, response);
}

void DecisionService::Stub::async::ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportDecision_, context, request, response, std::move(f));
}

void DecisionService::Stub::async::ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReportDecision_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>* DecisionService::Stub::PrepareAsyncReportDecisionRaw(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::decision::ReportDecisionResponse, ::decision::ReportDecisionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReportDecision_, context, request);
}

::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>* DecisionService::Stub::AsyncReportDecisionRaw(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReportDecisionRaw(context, request, cq);
  result->StartCall();
  return result;
}

DecisionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DecisionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DecisionService::Service, ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DecisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::decision::GetDecisionsRequest* req,
             ::decision::GetDecisionsResponse* resp) {
               return service->GetDecisions(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DecisionService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DecisionService::Service, ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DecisionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::decision::ReportDecisionRequest* req,
             ::decision::ReportDecisionResponse* resp) {
               return service->ReportDecision(ctx, req, resp);
             }, this)));
}

DecisionService::Service::~Service() {
}

::grpc::Status DecisionService::Service::GetDecisions(::grpc::ServerContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DecisionService::Service::ReportDecision(::grpc::ServerContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace decision

