// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: decision.proto
#ifndef GRPC_decision_2eproto__INCLUDED
#define GRPC_decision_2eproto__INCLUDED

#include "decision.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace decision {

class DecisionService final {
 public:
  static constexpr char const* service_full_name() {
    return "decision.DecisionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::decision::GetDecisionsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::GetDecisionsResponse>> AsyncGetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::GetDecisionsResponse>>(AsyncGetDecisionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::GetDecisionsResponse>> PrepareAsyncGetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::GetDecisionsResponse>>(PrepareAsyncGetDecisionsRaw(context, request, cq));
    }
    virtual ::grpc::Status ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::decision::ReportDecisionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::ReportDecisionResponse>> AsyncReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::ReportDecisionResponse>>(AsyncReportDecisionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::ReportDecisionResponse>> PrepareAsyncReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::decision::ReportDecisionResponse>>(PrepareAsyncReportDecisionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::decision::GetDecisionsResponse>* AsyncGetDecisionsRaw(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::decision::GetDecisionsResponse>* PrepareAsyncGetDecisionsRaw(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::decision::ReportDecisionResponse>* AsyncReportDecisionRaw(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::decision::ReportDecisionResponse>* PrepareAsyncReportDecisionRaw(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::decision::GetDecisionsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>> AsyncGetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>>(AsyncGetDecisionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>> PrepareAsyncGetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>>(PrepareAsyncGetDecisionsRaw(context, request, cq));
    }
    ::grpc::Status ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::decision::ReportDecisionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>> AsyncReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>>(AsyncReportDecisionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>> PrepareAsyncReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>>(PrepareAsyncReportDecisionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetDecisions(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response, std::function<void(::grpc::Status)>) override;
      void ReportDecision(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>* AsyncGetDecisionsRaw(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::decision::GetDecisionsResponse>* PrepareAsyncGetDecisionsRaw(::grpc::ClientContext* context, const ::decision::GetDecisionsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>* AsyncReportDecisionRaw(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::decision::ReportDecisionResponse>* PrepareAsyncReportDecisionRaw(::grpc::ClientContext* context, const ::decision::ReportDecisionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetDecisions_;
    const ::grpc::internal::RpcMethod rpcmethod_ReportDecision_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetDecisions(::grpc::ServerContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response);
    virtual ::grpc::Status ReportDecision(::grpc::ServerContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDecisions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDecisions() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetDecisions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDecisions(::grpc::ServerContext* /*context*/, const ::decision::GetDecisionsRequest* /*request*/, ::decision::GetDecisionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDecisions(::grpc::ServerContext* context, ::decision::GetDecisionsRequest* request, ::grpc::ServerAsyncResponseWriter< ::decision::GetDecisionsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReportDecision : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReportDecision() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReportDecision() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDecision(::grpc::ServerContext* /*context*/, const ::decision::ReportDecisionRequest* /*request*/, ::decision::ReportDecisionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportDecision(::grpc::ServerContext* context, ::decision::ReportDecisionRequest* request, ::grpc::ServerAsyncResponseWriter< ::decision::ReportDecisionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetDecisions<WithAsyncMethod_ReportDecision<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetDecisions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDecisions() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::decision::GetDecisionsRequest* request, ::decision::GetDecisionsResponse* response) { return this->GetDecisions(context, request, response); }));}
    void SetMessageAllocatorFor_GetDecisions(
        ::grpc::MessageAllocator< ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDecisions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDecisions(::grpc::ServerContext* /*context*/, const ::decision::GetDecisionsRequest* /*request*/, ::decision::GetDecisionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDecisions(
      ::grpc::CallbackServerContext* /*context*/, const ::decision::GetDecisionsRequest* /*request*/, ::decision::GetDecisionsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReportDecision : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReportDecision() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::decision::ReportDecisionRequest* request, ::decision::ReportDecisionResponse* response) { return this->ReportDecision(context, request, response); }));}
    void SetMessageAllocatorFor_ReportDecision(
        ::grpc::MessageAllocator< ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReportDecision() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDecision(::grpc::ServerContext* /*context*/, const ::decision::ReportDecisionRequest* /*request*/, ::decision::ReportDecisionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportDecision(
      ::grpc::CallbackServerContext* /*context*/, const ::decision::ReportDecisionRequest* /*request*/, ::decision::ReportDecisionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetDecisions<WithCallbackMethod_ReportDecision<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetDecisions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDecisions() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetDecisions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDecisions(::grpc::ServerContext* /*context*/, const ::decision::GetDecisionsRequest* /*request*/, ::decision::GetDecisionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReportDecision : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReportDecision() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReportDecision() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDecision(::grpc::ServerContext* /*context*/, const ::decision::ReportDecisionRequest* /*request*/, ::decision::ReportDecisionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDecisions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDecisions() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetDecisions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDecisions(::grpc::ServerContext* /*context*/, const ::decision::GetDecisionsRequest* /*request*/, ::decision::GetDecisionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDecisions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReportDecision : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReportDecision() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReportDecision() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDecision(::grpc::ServerContext* /*context*/, const ::decision::ReportDecisionRequest* /*request*/, ::decision::ReportDecisionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReportDecision(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDecisions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDecisions() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDecisions(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDecisions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDecisions(::grpc::ServerContext* /*context*/, const ::decision::GetDecisionsRequest* /*request*/, ::decision::GetDecisionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDecisions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReportDecision : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReportDecision() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReportDecision(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReportDecision() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReportDecision(::grpc::ServerContext* /*context*/, const ::decision::ReportDecisionRequest* /*request*/, ::decision::ReportDecisionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReportDecision(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDecisions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDecisions() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::decision::GetDecisionsRequest, ::decision::GetDecisionsResponse>* streamer) {
                       return this->StreamedGetDecisions(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDecisions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDecisions(::grpc::ServerContext* /*context*/, const ::decision::GetDecisionsRequest* /*request*/, ::decision::GetDecisionsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDecisions(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::decision::GetDecisionsRequest,::decision::GetDecisionsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReportDecision : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReportDecision() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::decision::ReportDecisionRequest, ::decision::ReportDecisionResponse>* streamer) {
                       return this->StreamedReportDecision(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReportDecision() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReportDecision(::grpc::ServerContext* /*context*/, const ::decision::ReportDecisionRequest* /*request*/, ::decision::ReportDecisionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReportDecision(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::decision::ReportDecisionRequest,::decision::ReportDecisionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetDecisions<WithStreamedUnaryMethod_ReportDecision<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetDecisions<WithStreamedUnaryMethod_ReportDecision<Service > > StreamedService;
};

}  // namespace decision


#endif  // GRPC_decision_2eproto__INCLUDED
