// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: monitoring.proto
#ifndef GRPC_monitoring_2eproto__INCLUDED
#define GRPC_monitoring_2eproto__INCLUDED

#include "monitoring.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace monitoring {

class MonitoringService final {
 public:
  static constexpr char const* service_full_name() {
    return "monitoring.MonitoringService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::HealthResponse>> AsyncGetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::HealthResponse>>(AsyncGetSystemHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::HealthResponse>> PrepareAsyncGetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::HealthResponse>>(PrepareAsyncGetSystemHealthRaw(context, request, cq));
    }
    virtual ::grpc::Status GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::ActionDistributionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::ActionDistributionResponse>> AsyncGetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::ActionDistributionResponse>>(AsyncGetActionDistributionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::ActionDistributionResponse>> PrepareAsyncGetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::ActionDistributionResponse>>(PrepareAsyncGetActionDistributionRaw(context, request, cq));
    }
    virtual ::grpc::Status GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::AdoptionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::AdoptionResponse>> AsyncGetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::AdoptionResponse>>(AsyncGetAdoptionRateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::AdoptionResponse>> PrepareAsyncGetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::AdoptionResponse>>(PrepareAsyncGetAdoptionRateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::HealthResponse>* AsyncGetSystemHealthRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::HealthResponse>* PrepareAsyncGetSystemHealthRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::ActionDistributionResponse>* AsyncGetActionDistributionRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::ActionDistributionResponse>* PrepareAsyncGetActionDistributionRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::AdoptionResponse>* AsyncGetAdoptionRateRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::monitoring::AdoptionResponse>* PrepareAsyncGetAdoptionRateRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>> AsyncGetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>>(AsyncGetSystemHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>> PrepareAsyncGetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>>(PrepareAsyncGetSystemHealthRaw(context, request, cq));
    }
    ::grpc::Status GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::ActionDistributionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>> AsyncGetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>>(AsyncGetActionDistributionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>> PrepareAsyncGetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>>(PrepareAsyncGetActionDistributionRaw(context, request, cq));
    }
    ::grpc::Status GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::AdoptionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>> AsyncGetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>>(AsyncGetAdoptionRateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>> PrepareAsyncGetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>>(PrepareAsyncGetAdoptionRateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response, std::function<void(::grpc::Status)>) override;
      void GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response, std::function<void(::grpc::Status)>) override;
      void GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>* AsyncGetSystemHealthRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>* PrepareAsyncGetSystemHealthRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>* AsyncGetActionDistributionRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>* PrepareAsyncGetActionDistributionRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>* AsyncGetAdoptionRateRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>* PrepareAsyncGetAdoptionRateRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetSystemHealth_;
    const ::grpc::internal::RpcMethod rpcmethod_GetActionDistribution_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAdoptionRate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSystemHealth(::grpc::ServerContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response);
    virtual ::grpc::Status GetActionDistribution(::grpc::ServerContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response);
    virtual ::grpc::Status GetAdoptionRate(::grpc::ServerContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSystemHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetSystemHealth() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSystemHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemHealth(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSystemHealth(::grpc::ServerContext* context, ::monitoring::Empty* request, ::grpc::ServerAsyncResponseWriter< ::monitoring::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetActionDistribution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetActionDistribution() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetActionDistribution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetActionDistribution(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::ActionDistributionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetActionDistribution(::grpc::ServerContext* context, ::monitoring::Empty* request, ::grpc::ServerAsyncResponseWriter< ::monitoring::ActionDistributionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAdoptionRate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAdoptionRate() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetAdoptionRate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAdoptionRate(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::AdoptionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAdoptionRate(::grpc::ServerContext* context, ::monitoring::Empty* request, ::grpc::ServerAsyncResponseWriter< ::monitoring::AdoptionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSystemHealth<WithAsyncMethod_GetActionDistribution<WithAsyncMethod_GetAdoptionRate<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetSystemHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetSystemHealth() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::monitoring::Empty, ::monitoring::HealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response) { return this->GetSystemHealth(context, request, response); }));}
    void SetMessageAllocatorFor_GetSystemHealth(
        ::grpc::MessageAllocator< ::monitoring::Empty, ::monitoring::HealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::monitoring::Empty, ::monitoring::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetSystemHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemHealth(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSystemHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::HealthResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetActionDistribution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetActionDistribution() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::monitoring::Empty, ::monitoring::ActionDistributionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response) { return this->GetActionDistribution(context, request, response); }));}
    void SetMessageAllocatorFor_GetActionDistribution(
        ::grpc::MessageAllocator< ::monitoring::Empty, ::monitoring::ActionDistributionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::monitoring::Empty, ::monitoring::ActionDistributionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetActionDistribution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetActionDistribution(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::ActionDistributionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetActionDistribution(
      ::grpc::CallbackServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::ActionDistributionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetAdoptionRate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetAdoptionRate() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::monitoring::Empty, ::monitoring::AdoptionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response) { return this->GetAdoptionRate(context, request, response); }));}
    void SetMessageAllocatorFor_GetAdoptionRate(
        ::grpc::MessageAllocator< ::monitoring::Empty, ::monitoring::AdoptionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::monitoring::Empty, ::monitoring::AdoptionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetAdoptionRate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAdoptionRate(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::AdoptionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAdoptionRate(
      ::grpc::CallbackServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::AdoptionResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetSystemHealth<WithCallbackMethod_GetActionDistribution<WithCallbackMethod_GetAdoptionRate<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetSystemHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetSystemHealth() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSystemHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemHealth(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetActionDistribution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetActionDistribution() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetActionDistribution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetActionDistribution(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::ActionDistributionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAdoptionRate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAdoptionRate() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetAdoptionRate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAdoptionRate(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::AdoptionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSystemHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetSystemHealth() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetSystemHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemHealth(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSystemHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetActionDistribution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetActionDistribution() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetActionDistribution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetActionDistribution(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::ActionDistributionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetActionDistribution(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAdoptionRate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAdoptionRate() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetAdoptionRate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAdoptionRate(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::AdoptionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAdoptionRate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetSystemHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetSystemHealth() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetSystemHealth(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetSystemHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSystemHealth(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetSystemHealth(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetActionDistribution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetActionDistribution() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetActionDistribution(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetActionDistribution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetActionDistribution(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::ActionDistributionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetActionDistribution(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetAdoptionRate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetAdoptionRate() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAdoptionRate(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetAdoptionRate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAdoptionRate(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::AdoptionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetAdoptionRate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSystemHealth : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetSystemHealth() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::monitoring::Empty, ::monitoring::HealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::monitoring::Empty, ::monitoring::HealthResponse>* streamer) {
                       return this->StreamedGetSystemHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetSystemHealth() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSystemHealth(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSystemHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::monitoring::Empty,::monitoring::HealthResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetActionDistribution : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetActionDistribution() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::monitoring::Empty, ::monitoring::ActionDistributionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::monitoring::Empty, ::monitoring::ActionDistributionResponse>* streamer) {
                       return this->StreamedGetActionDistribution(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetActionDistribution() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetActionDistribution(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::ActionDistributionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetActionDistribution(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::monitoring::Empty,::monitoring::ActionDistributionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAdoptionRate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAdoptionRate() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::monitoring::Empty, ::monitoring::AdoptionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::monitoring::Empty, ::monitoring::AdoptionResponse>* streamer) {
                       return this->StreamedGetAdoptionRate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAdoptionRate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAdoptionRate(::grpc::ServerContext* /*context*/, const ::monitoring::Empty* /*request*/, ::monitoring::AdoptionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAdoptionRate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::monitoring::Empty,::monitoring::AdoptionResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetSystemHealth<WithStreamedUnaryMethod_GetActionDistribution<WithStreamedUnaryMethod_GetAdoptionRate<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetSystemHealth<WithStreamedUnaryMethod_GetActionDistribution<WithStreamedUnaryMethod_GetAdoptionRate<Service > > > StreamedService;
};

}  // namespace monitoring


#endif  // GRPC_monitoring_2eproto__INCLUDED
