// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: monitoring.proto

#include "monitoring.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace monitoring {
PROTOBUF_CONSTEXPR Empty::Empty(
    ::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
PROTOBUF_CONSTEXPR HealthResponse::HealthResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.server_ok_)*/false
  , /*decltype(_impl_.grpc_ok_)*/false
  , /*decltype(_impl_.bandit_ok_)*/false
  , /*decltype(_impl_.latency_ms_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HealthResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthResponseDefaultTypeInternal() {}
  union {
    HealthResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthResponseDefaultTypeInternal _HealthResponse_default_instance_;
PROTOBUF_CONSTEXPR ActionDistributionResponse::ActionDistributionResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.inspect_)*/0
  , /*decltype(_impl_.no_action_)*/0
  , /*decltype(_impl_.alert_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ActionDistributionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActionDistributionResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActionDistributionResponseDefaultTypeInternal() {}
  union {
    ActionDistributionResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActionDistributionResponseDefaultTypeInternal _ActionDistributionResponse_default_instance_;
PROTOBUF_CONSTEXPR AdoptionResponse::AdoptionResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.history_)*/{}
  , /*decltype(_impl_.adoption_rate_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AdoptionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AdoptionResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AdoptionResponseDefaultTypeInternal() {}
  union {
    AdoptionResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AdoptionResponseDefaultTypeInternal _AdoptionResponse_default_instance_;
}  // namespace monitoring
static ::_pb::Metadata file_level_metadata_monitoring_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_monitoring_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_monitoring_2eproto = nullptr;

const uint32_t TableStruct_monitoring_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitoring::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitoring::HealthResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::monitoring::HealthResponse, _impl_.server_ok_),
  PROTOBUF_FIELD_OFFSET(::monitoring::HealthResponse, _impl_.grpc_ok_),
  PROTOBUF_FIELD_OFFSET(::monitoring::HealthResponse, _impl_.bandit_ok_),
  PROTOBUF_FIELD_OFFSET(::monitoring::HealthResponse, _impl_.latency_ms_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitoring::ActionDistributionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::monitoring::ActionDistributionResponse, _impl_.inspect_),
  PROTOBUF_FIELD_OFFSET(::monitoring::ActionDistributionResponse, _impl_.no_action_),
  PROTOBUF_FIELD_OFFSET(::monitoring::ActionDistributionResponse, _impl_.alert_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::monitoring::AdoptionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::monitoring::AdoptionResponse, _impl_.adoption_rate_),
  PROTOBUF_FIELD_OFFSET(::monitoring::AdoptionResponse, _impl_.history_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::monitoring::Empty)},
  { 6, -1, -1, sizeof(::monitoring::HealthResponse)},
  { 16, -1, -1, sizeof(::monitoring::ActionDistributionResponse)},
  { 25, -1, -1, sizeof(::monitoring::AdoptionResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::monitoring::_Empty_default_instance_._instance,
  &::monitoring::_HealthResponse_default_instance_._instance,
  &::monitoring::_ActionDistributionResponse_default_instance_._instance,
  &::monitoring::_AdoptionResponse_default_instance_._instance,
};

const char descriptor_table_protodef_monitoring_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020monitoring.proto\022\nmonitoring\"\007\n\005Empty\""
  "[\n\016HealthResponse\022\021\n\tserver_ok\030\001 \001(\010\022\017\n\007"
  "grpc_ok\030\002 \001(\010\022\021\n\tbandit_ok\030\003 \001(\010\022\022\n\nlate"
  "ncy_ms\030\004 \001(\005\"O\n\032ActionDistributionRespon"
  "se\022\017\n\007inspect\030\001 \001(\005\022\021\n\tno_action\030\002 \001(\005\022\r"
  "\n\005alert\030\003 \001(\005\":\n\020AdoptionResponse\022\025\n\rado"
  "ption_rate\030\001 \001(\001\022\017\n\007history\030\002 \003(\0012\355\001\n\021Mo"
  "nitoringService\022@\n\017GetSystemHealth\022\021.mon"
  "itoring.Empty\032\032.monitoring.HealthRespons"
  "e\022R\n\025GetActionDistribution\022\021.monitoring."
  "Empty\032&.monitoring.ActionDistributionRes"
  "ponse\022B\n\017GetAdoptionRate\022\021.monitoring.Em"
  "pty\032\034.monitoring.AdoptionResponseb\006proto"
  "3"
  ;
static ::_pbi::once_flag descriptor_table_monitoring_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_monitoring_2eproto = {
    false, false, 521, descriptor_table_protodef_monitoring_2eproto,
    "monitoring.proto",
    &descriptor_table_monitoring_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_monitoring_2eproto::offsets,
    file_level_metadata_monitoring_2eproto, file_level_enum_descriptors_monitoring_2eproto,
    file_level_service_descriptors_monitoring_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_monitoring_2eproto_getter() {
  return &descriptor_table_monitoring_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_monitoring_2eproto(&descriptor_table_monitoring_2eproto);
namespace monitoring {

// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:monitoring.Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Empty* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:monitoring.Empty)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Empty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Empty::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_monitoring_2eproto_getter, &descriptor_table_monitoring_2eproto_once,
      file_level_metadata_monitoring_2eproto[0]);
}

// ===================================================================

class HealthResponse::_Internal {
 public:
};

HealthResponse::HealthResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:monitoring.HealthResponse)
}
HealthResponse::HealthResponse(const HealthResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HealthResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.server_ok_){}
    , decltype(_impl_.grpc_ok_){}
    , decltype(_impl_.bandit_ok_){}
    , decltype(_impl_.latency_ms_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.server_ok_, &from._impl_.server_ok_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.latency_ms_) -
    reinterpret_cast<char*>(&_impl_.server_ok_)) + sizeof(_impl_.latency_ms_));
  // @@protoc_insertion_point(copy_constructor:monitoring.HealthResponse)
}

inline void HealthResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.server_ok_){false}
    , decltype(_impl_.grpc_ok_){false}
    , decltype(_impl_.bandit_ok_){false}
    , decltype(_impl_.latency_ms_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HealthResponse::~HealthResponse() {
  // @@protoc_insertion_point(destructor:monitoring.HealthResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HealthResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HealthResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HealthResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:monitoring.HealthResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.server_ok_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.latency_ms_) -
      reinterpret_cast<char*>(&_impl_.server_ok_)) + sizeof(_impl_.latency_ms_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HealthResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool server_ok = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.server_ok_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool grpc_ok = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.grpc_ok_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool bandit_ok = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.bandit_ok_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 latency_ms = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.latency_ms_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HealthResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitoring.HealthResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool server_ok = 1;
  if (this->_internal_server_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_server_ok(), target);
  }

  // bool grpc_ok = 2;
  if (this->_internal_grpc_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_grpc_ok(), target);
  }

  // bool bandit_ok = 3;
  if (this->_internal_bandit_ok() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_bandit_ok(), target);
  }

  // int32 latency_ms = 4;
  if (this->_internal_latency_ms() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_latency_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitoring.HealthResponse)
  return target;
}

size_t HealthResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitoring.HealthResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool server_ok = 1;
  if (this->_internal_server_ok() != 0) {
    total_size += 1 + 1;
  }

  // bool grpc_ok = 2;
  if (this->_internal_grpc_ok() != 0) {
    total_size += 1 + 1;
  }

  // bool bandit_ok = 3;
  if (this->_internal_bandit_ok() != 0) {
    total_size += 1 + 1;
  }

  // int32 latency_ms = 4;
  if (this->_internal_latency_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_latency_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HealthResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HealthResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HealthResponse::GetClassData() const { return &_class_data_; }


void HealthResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HealthResponse*>(&to_msg);
  auto& from = static_cast<const HealthResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:monitoring.HealthResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_server_ok() != 0) {
    _this->_internal_set_server_ok(from._internal_server_ok());
  }
  if (from._internal_grpc_ok() != 0) {
    _this->_internal_set_grpc_ok(from._internal_grpc_ok());
  }
  if (from._internal_bandit_ok() != 0) {
    _this->_internal_set_bandit_ok(from._internal_bandit_ok());
  }
  if (from._internal_latency_ms() != 0) {
    _this->_internal_set_latency_ms(from._internal_latency_ms());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HealthResponse::CopyFrom(const HealthResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitoring.HealthResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HealthResponse::IsInitialized() const {
  return true;
}

void HealthResponse::InternalSwap(HealthResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.latency_ms_)
      + sizeof(HealthResponse::_impl_.latency_ms_)
      - PROTOBUF_FIELD_OFFSET(HealthResponse, _impl_.server_ok_)>(
          reinterpret_cast<char*>(&_impl_.server_ok_),
          reinterpret_cast<char*>(&other->_impl_.server_ok_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HealthResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_monitoring_2eproto_getter, &descriptor_table_monitoring_2eproto_once,
      file_level_metadata_monitoring_2eproto[1]);
}

// ===================================================================

class ActionDistributionResponse::_Internal {
 public:
};

ActionDistributionResponse::ActionDistributionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:monitoring.ActionDistributionResponse)
}
ActionDistributionResponse::ActionDistributionResponse(const ActionDistributionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ActionDistributionResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.inspect_){}
    , decltype(_impl_.no_action_){}
    , decltype(_impl_.alert_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.inspect_, &from._impl_.inspect_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.alert_) -
    reinterpret_cast<char*>(&_impl_.inspect_)) + sizeof(_impl_.alert_));
  // @@protoc_insertion_point(copy_constructor:monitoring.ActionDistributionResponse)
}

inline void ActionDistributionResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.inspect_){0}
    , decltype(_impl_.no_action_){0}
    , decltype(_impl_.alert_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ActionDistributionResponse::~ActionDistributionResponse() {
  // @@protoc_insertion_point(destructor:monitoring.ActionDistributionResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActionDistributionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ActionDistributionResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ActionDistributionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:monitoring.ActionDistributionResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.inspect_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.alert_) -
      reinterpret_cast<char*>(&_impl_.inspect_)) + sizeof(_impl_.alert_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionDistributionResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 inspect = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.inspect_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 no_action = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.no_action_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 alert = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.alert_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActionDistributionResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitoring.ActionDistributionResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 inspect = 1;
  if (this->_internal_inspect() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_inspect(), target);
  }

  // int32 no_action = 2;
  if (this->_internal_no_action() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_no_action(), target);
  }

  // int32 alert = 3;
  if (this->_internal_alert() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_alert(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitoring.ActionDistributionResponse)
  return target;
}

size_t ActionDistributionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitoring.ActionDistributionResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 inspect = 1;
  if (this->_internal_inspect() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_inspect());
  }

  // int32 no_action = 2;
  if (this->_internal_no_action() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_no_action());
  }

  // int32 alert = 3;
  if (this->_internal_alert() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_alert());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActionDistributionResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ActionDistributionResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActionDistributionResponse::GetClassData() const { return &_class_data_; }


void ActionDistributionResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ActionDistributionResponse*>(&to_msg);
  auto& from = static_cast<const ActionDistributionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:monitoring.ActionDistributionResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_inspect() != 0) {
    _this->_internal_set_inspect(from._internal_inspect());
  }
  if (from._internal_no_action() != 0) {
    _this->_internal_set_no_action(from._internal_no_action());
  }
  if (from._internal_alert() != 0) {
    _this->_internal_set_alert(from._internal_alert());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActionDistributionResponse::CopyFrom(const ActionDistributionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitoring.ActionDistributionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionDistributionResponse::IsInitialized() const {
  return true;
}

void ActionDistributionResponse::InternalSwap(ActionDistributionResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ActionDistributionResponse, _impl_.alert_)
      + sizeof(ActionDistributionResponse::_impl_.alert_)
      - PROTOBUF_FIELD_OFFSET(ActionDistributionResponse, _impl_.inspect_)>(
          reinterpret_cast<char*>(&_impl_.inspect_),
          reinterpret_cast<char*>(&other->_impl_.inspect_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionDistributionResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_monitoring_2eproto_getter, &descriptor_table_monitoring_2eproto_once,
      file_level_metadata_monitoring_2eproto[2]);
}

// ===================================================================

class AdoptionResponse::_Internal {
 public:
};

AdoptionResponse::AdoptionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:monitoring.AdoptionResponse)
}
AdoptionResponse::AdoptionResponse(const AdoptionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AdoptionResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.history_){from._impl_.history_}
    , decltype(_impl_.adoption_rate_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.adoption_rate_ = from._impl_.adoption_rate_;
  // @@protoc_insertion_point(copy_constructor:monitoring.AdoptionResponse)
}

inline void AdoptionResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.history_){arena}
    , decltype(_impl_.adoption_rate_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AdoptionResponse::~AdoptionResponse() {
  // @@protoc_insertion_point(destructor:monitoring.AdoptionResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AdoptionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.history_.~RepeatedField();
}

void AdoptionResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AdoptionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:monitoring.AdoptionResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.history_.Clear();
  _impl_.adoption_rate_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AdoptionResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double adoption_rate = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _impl_.adoption_rate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // repeated double history = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_history(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 17) {
          _internal_add_history(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AdoptionResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:monitoring.AdoptionResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // double adoption_rate = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_adoption_rate = this->_internal_adoption_rate();
  uint64_t raw_adoption_rate;
  memcpy(&raw_adoption_rate, &tmp_adoption_rate, sizeof(tmp_adoption_rate));
  if (raw_adoption_rate != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(1, this->_internal_adoption_rate(), target);
  }

  // repeated double history = 2;
  if (this->_internal_history_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_history(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:monitoring.AdoptionResponse)
  return target;
}

size_t AdoptionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:monitoring.AdoptionResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double history = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_history_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // double adoption_rate = 1;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_adoption_rate = this->_internal_adoption_rate();
  uint64_t raw_adoption_rate;
  memcpy(&raw_adoption_rate, &tmp_adoption_rate, sizeof(tmp_adoption_rate));
  if (raw_adoption_rate != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AdoptionResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AdoptionResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AdoptionResponse::GetClassData() const { return &_class_data_; }


void AdoptionResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AdoptionResponse*>(&to_msg);
  auto& from = static_cast<const AdoptionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:monitoring.AdoptionResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.history_.MergeFrom(from._impl_.history_);
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_adoption_rate = from._internal_adoption_rate();
  uint64_t raw_adoption_rate;
  memcpy(&raw_adoption_rate, &tmp_adoption_rate, sizeof(tmp_adoption_rate));
  if (raw_adoption_rate != 0) {
    _this->_internal_set_adoption_rate(from._internal_adoption_rate());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AdoptionResponse::CopyFrom(const AdoptionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:monitoring.AdoptionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AdoptionResponse::IsInitialized() const {
  return true;
}

void AdoptionResponse::InternalSwap(AdoptionResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.history_.InternalSwap(&other->_impl_.history_);
  swap(_impl_.adoption_rate_, other->_impl_.adoption_rate_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AdoptionResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_monitoring_2eproto_getter, &descriptor_table_monitoring_2eproto_once,
      file_level_metadata_monitoring_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace monitoring
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::monitoring::Empty*
Arena::CreateMaybeMessage< ::monitoring::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitoring::Empty >(arena);
}
template<> PROTOBUF_NOINLINE ::monitoring::HealthResponse*
Arena::CreateMaybeMessage< ::monitoring::HealthResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitoring::HealthResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::monitoring::ActionDistributionResponse*
Arena::CreateMaybeMessage< ::monitoring::ActionDistributionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitoring::ActionDistributionResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::monitoring::AdoptionResponse*
Arena::CreateMaybeMessage< ::monitoring::AdoptionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::monitoring::AdoptionResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
