// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bi.proto

#include "bi.pb.h"
#include "bi.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace bi {

static const char* BIReportService_method_names[] = {
  "/bi.BIReportService/GenerateReport",
  "/bi.BIReportService/ExportReport",
  "/bi.BIReportService/GetReports",
  "/bi.BIReportService/GetReport",
  "/bi.BIReportService/DeleteReport",
  "/bi.BIReportService/AddTask",
  "/bi.BIReportService/GetTasks",
  "/bi.BIReportService/UpdateTask",
  "/bi.BIReportService/DeleteTask",
};

std::unique_ptr< BIReportService::Stub> BIReportService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BIReportService::Stub> stub(new BIReportService::Stub(channel, options));
  return stub;
}

BIReportService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GenerateReport_(BIReportService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExportReport_(BIReportService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetReports_(BIReportService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetReport_(BIReportService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteReport_(BIReportService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddTask_(BIReportService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTasks_(BIReportService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateTask_(BIReportService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteTask_(BIReportService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BIReportService::Stub::GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::bi::GenerateReportResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::GenerateReportRequest, ::bi::GenerateReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GenerateReport_, context, request, response);
}

void BIReportService::Stub::async::GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::GenerateReportRequest, ::bi::GenerateReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateReport_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::GenerateReport(::grpc::ClientContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GenerateReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>* BIReportService::Stub::PrepareAsyncGenerateReportRaw(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::GenerateReportResponse, ::bi::GenerateReportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GenerateReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::GenerateReportResponse>* BIReportService::Stub::AsyncGenerateReportRaw(::grpc::ClientContext* context, const ::bi::GenerateReportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGenerateReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::bi::ExportReportResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::ExportReportRequest, ::bi::ExportReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExportReport_, context, request, response);
}

void BIReportService::Stub::async::ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::ExportReportRequest, ::bi::ExportReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExportReport_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::ExportReport(::grpc::ClientContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExportReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>* BIReportService::Stub::PrepareAsyncExportReportRaw(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::ExportReportResponse, ::bi::ExportReportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExportReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::ExportReportResponse>* BIReportService::Stub::AsyncExportReportRaw(::grpc::ClientContext* context, const ::bi::ExportReportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExportReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::bi::GetReportsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::GetReportsRequest, ::bi::GetReportsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetReports_, context, request, response);
}

void BIReportService::Stub::async::GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::GetReportsRequest, ::bi::GetReportsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReports_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::GetReports(::grpc::ClientContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReports_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>* BIReportService::Stub::PrepareAsyncGetReportsRaw(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::GetReportsResponse, ::bi::GetReportsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetReports_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::GetReportsResponse>* BIReportService::Stub::AsyncGetReportsRaw(::grpc::ClientContext* context, const ::bi::GetReportsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetReportsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::bi::ReportResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::GetReportRequest, ::bi::ReportResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetReport_, context, request, response);
}

void BIReportService::Stub::async::GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::GetReportRequest, ::bi::ReportResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReport_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::GetReport(::grpc::ClientContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::ReportResult>* BIReportService::Stub::PrepareAsyncGetReportRaw(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::ReportResult, ::bi::GetReportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::ReportResult>* BIReportService::Stub::AsyncGetReportRaw(::grpc::ClientContext* context, const ::bi::GetReportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::bi::DeleteReportResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::DeleteReportRequest, ::bi::DeleteReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteReport_, context, request, response);
}

void BIReportService::Stub::async::DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::DeleteReportRequest, ::bi::DeleteReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteReport_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::DeleteReport(::grpc::ClientContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>* BIReportService::Stub::PrepareAsyncDeleteReportRaw(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::DeleteReportResponse, ::bi::DeleteReportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::DeleteReportResponse>* BIReportService::Stub::AsyncDeleteReportRaw(::grpc::ClientContext* context, const ::bi::DeleteReportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::bi::AddTaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::AddTaskRequest, ::bi::AddTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddTask_, context, request, response);
}

void BIReportService::Stub::async::AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::AddTaskRequest, ::bi::AddTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTask_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::AddTask(::grpc::ClientContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>* BIReportService::Stub::PrepareAsyncAddTaskRaw(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::AddTaskResponse, ::bi::AddTaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::AddTaskResponse>* BIReportService::Stub::AsyncAddTaskRaw(::grpc::ClientContext* context, const ::bi::AddTaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::bi::GetTasksResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::GetTasksRequest, ::bi::GetTasksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTasks_, context, request, response);
}

void BIReportService::Stub::async::GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::GetTasksRequest, ::bi::GetTasksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTasks_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::GetTasks(::grpc::ClientContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTasks_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>* BIReportService::Stub::PrepareAsyncGetTasksRaw(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::GetTasksResponse, ::bi::GetTasksRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTasks_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::GetTasksResponse>* BIReportService::Stub::AsyncGetTasksRaw(::grpc::ClientContext* context, const ::bi::GetTasksRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTasksRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::bi::UpdateTaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateTask_, context, request, response);
}

void BIReportService::Stub::async::UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateTask_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::UpdateTask(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>* BIReportService::Stub::PrepareAsyncUpdateTaskRaw(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::UpdateTaskResponse, ::bi::UpdateTaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::UpdateTaskResponse>* BIReportService::Stub::AsyncUpdateTaskRaw(::grpc::ClientContext* context, const ::bi::UpdateTaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status BIReportService::Stub::DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::bi::DeleteTaskResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteTask_, context, request, response);
}

void BIReportService::Stub::async::DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteTask_, context, request, response, std::move(f));
}

void BIReportService::Stub::async::DeleteTask(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteTask_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>* BIReportService::Stub::PrepareAsyncDeleteTaskRaw(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bi::DeleteTaskResponse, ::bi::DeleteTaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteTask_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bi::DeleteTaskResponse>* BIReportService::Stub::AsyncDeleteTaskRaw(::grpc::ClientContext* context, const ::bi::DeleteTaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteTaskRaw(context, request, cq);
  result->StartCall();
  return result;
}

BIReportService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::GenerateReportRequest, ::bi::GenerateReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::GenerateReportRequest* req,
             ::bi::GenerateReportResponse* resp) {
               return service->GenerateReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::ExportReportRequest, ::bi::ExportReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::ExportReportRequest* req,
             ::bi::ExportReportResponse* resp) {
               return service->ExportReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::GetReportsRequest, ::bi::GetReportsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::GetReportsRequest* req,
             ::bi::GetReportsResponse* resp) {
               return service->GetReports(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::GetReportRequest, ::bi::ReportResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::GetReportRequest* req,
             ::bi::ReportResult* resp) {
               return service->GetReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::DeleteReportRequest, ::bi::DeleteReportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::DeleteReportRequest* req,
             ::bi::DeleteReportResponse* resp) {
               return service->DeleteReport(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::AddTaskRequest, ::bi::AddTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::AddTaskRequest* req,
             ::bi::AddTaskResponse* resp) {
               return service->AddTask(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::GetTasksRequest, ::bi::GetTasksResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::GetTasksRequest* req,
             ::bi::GetTasksResponse* resp) {
               return service->GetTasks(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::UpdateTaskRequest, ::bi::UpdateTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::UpdateTaskRequest* req,
             ::bi::UpdateTaskResponse* resp) {
               return service->UpdateTask(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BIReportService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BIReportService::Service, ::bi::DeleteTaskRequest, ::bi::DeleteTaskResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BIReportService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bi::DeleteTaskRequest* req,
             ::bi::DeleteTaskResponse* resp) {
               return service->DeleteTask(ctx, req, resp);
             }, this)));
}

BIReportService::Service::~Service() {
}

::grpc::Status BIReportService::Service::GenerateReport(::grpc::ServerContext* context, const ::bi::GenerateReportRequest* request, ::bi::GenerateReportResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::ExportReport(::grpc::ServerContext* context, const ::bi::ExportReportRequest* request, ::bi::ExportReportResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::GetReports(::grpc::ServerContext* context, const ::bi::GetReportsRequest* request, ::bi::GetReportsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::GetReport(::grpc::ServerContext* context, const ::bi::GetReportRequest* request, ::bi::ReportResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::DeleteReport(::grpc::ServerContext* context, const ::bi::DeleteReportRequest* request, ::bi::DeleteReportResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::AddTask(::grpc::ServerContext* context, const ::bi::AddTaskRequest* request, ::bi::AddTaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::GetTasks(::grpc::ServerContext* context, const ::bi::GetTasksRequest* request, ::bi::GetTasksResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::UpdateTask(::grpc::ServerContext* context, const ::bi::UpdateTaskRequest* request, ::bi::UpdateTaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status BIReportService::Service::DeleteTask(::grpc::ServerContext* context, const ::bi::DeleteTaskRequest* request, ::bi::DeleteTaskResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bi

