// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: monitoring.proto

#include "monitoring.pb.h"
#include "monitoring.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace monitoring {

static const char* MonitoringService_method_names[] = {
  "/monitoring.MonitoringService/GetSystemHealth",
  "/monitoring.MonitoringService/GetActionDistribution",
  "/monitoring.MonitoringService/GetAdoptionRate",
};

std::unique_ptr< MonitoringService::Stub> MonitoringService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MonitoringService::Stub> stub(new MonitoringService::Stub(channel, options));
  return stub;
}

MonitoringService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetSystemHealth_(MonitoringService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetActionDistribution_(MonitoringService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetAdoptionRate_(MonitoringService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MonitoringService::Stub::GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::monitoring::Empty, ::monitoring::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSystemHealth_, context, request, response);
}

void MonitoringService::Stub::async::GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::monitoring::Empty, ::monitoring::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSystemHealth_, context, request, response, std::move(f));
}

void MonitoringService::Stub::async::GetSystemHealth(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSystemHealth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>* MonitoringService::Stub::PrepareAsyncGetSystemHealthRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::monitoring::HealthResponse, ::monitoring::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSystemHealth_, context, request);
}

::grpc::ClientAsyncResponseReader< ::monitoring::HealthResponse>* MonitoringService::Stub::AsyncGetSystemHealthRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSystemHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MonitoringService::Stub::GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::ActionDistributionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::monitoring::Empty, ::monitoring::ActionDistributionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetActionDistribution_, context, request, response);
}

void MonitoringService::Stub::async::GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::monitoring::Empty, ::monitoring::ActionDistributionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActionDistribution_, context, request, response, std::move(f));
}

void MonitoringService::Stub::async::GetActionDistribution(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActionDistribution_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>* MonitoringService::Stub::PrepareAsyncGetActionDistributionRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::monitoring::ActionDistributionResponse, ::monitoring::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetActionDistribution_, context, request);
}

::grpc::ClientAsyncResponseReader< ::monitoring::ActionDistributionResponse>* MonitoringService::Stub::AsyncGetActionDistributionRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetActionDistributionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status MonitoringService::Stub::GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::monitoring::AdoptionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::monitoring::Empty, ::monitoring::AdoptionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetAdoptionRate_, context, request, response);
}

void MonitoringService::Stub::async::GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::monitoring::Empty, ::monitoring::AdoptionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAdoptionRate_, context, request, response, std::move(f));
}

void MonitoringService::Stub::async::GetAdoptionRate(::grpc::ClientContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetAdoptionRate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>* MonitoringService::Stub::PrepareAsyncGetAdoptionRateRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::monitoring::AdoptionResponse, ::monitoring::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetAdoptionRate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::monitoring::AdoptionResponse>* MonitoringService::Stub::AsyncGetAdoptionRateRaw(::grpc::ClientContext* context, const ::monitoring::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetAdoptionRateRaw(context, request, cq);
  result->StartCall();
  return result;
}

MonitoringService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitoringService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MonitoringService::Service, ::monitoring::Empty, ::monitoring::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MonitoringService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::monitoring::Empty* req,
             ::monitoring::HealthResponse* resp) {
               return service->GetSystemHealth(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitoringService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MonitoringService::Service, ::monitoring::Empty, ::monitoring::ActionDistributionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MonitoringService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::monitoring::Empty* req,
             ::monitoring::ActionDistributionResponse* resp) {
               return service->GetActionDistribution(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MonitoringService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MonitoringService::Service, ::monitoring::Empty, ::monitoring::AdoptionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MonitoringService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::monitoring::Empty* req,
             ::monitoring::AdoptionResponse* resp) {
               return service->GetAdoptionRate(ctx, req, resp);
             }, this)));
}

MonitoringService::Service::~Service() {
}

::grpc::Status MonitoringService::Service::GetSystemHealth(::grpc::ServerContext* context, const ::monitoring::Empty* request, ::monitoring::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MonitoringService::Service::GetActionDistribution(::grpc::ServerContext* context, const ::monitoring::Empty* request, ::monitoring::ActionDistributionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MonitoringService::Service::GetAdoptionRate(::grpc::ServerContext* context, const ::monitoring::Empty* request, ::monitoring::AdoptionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace monitoring

